// Everything "La Potion" says, in fr / es / en.
// Two sets of colour names (keys = NAMED_COLORS in mixing.js):
//   potion.color.*  as an adjective for "potion" (French/Spanish agree: "bleue", "roja")
//   potion.name.*   as a noun ("rouge et bleu, ça fait violet")
// potion.n.* are numbers in words, agreeing with "goutte"/"gota" (feminine).
export default {
  fr: {
    'potion.chooseLevel': 'Choisis un niveau !',
    'potion.ask': 'Je voudrais une potion {color}, s’il te plaît !',
    'potion.askRecipe': 'Je voudrais une potion avec {recipe}, s’il te plaît !',
    'potion.howTo': 'Glisse les couleurs dans le chaudron, puis mélange avec la cuillère !',
    'potion.stir': 'Mélanger',
    'potion.empty': 'Vider le chaudron',
    'potion.full': 'Le chaudron est plein ! Mélange ou vide-le.',
    'potion.success.simple': 'Merci ! C’est parfait !',
    'potion.success.mix': '{list}, ça fait {result} ! Merci !',
    'potion.success.count': 'Bravo, tu as bien compté ! Ça fait {result} !',
    'potion.wrong.1': 'Oups ! Ce n’est pas la bonne couleur. Essaie encore !',
    'potion.wrong.2': 'Hi hi, ça chatouille ! Mais ce n’est pas ma couleur.',
    'potion.wrong.3': 'Hmm… pas tout à fait ! On essaie encore ?',
    'potion.hint': 'Regarde les couleurs qui brillent !',
    'potion.hintEmpty': 'Vide le chaudron, et regarde les couleurs qui brillent !',
    'potion.hintCount': 'Compte bien les gouttes ! Regarde les points.',
    'potion.hintMore': 'Presque ! Ajoute encore un peu de {color} !',
    'potion.levelDone': 'Bravo ! Tu as fini le niveau !',
    'potion.freeIntro': 'Le labo est à toi ! Mélange toutes les couleurs que tu veux !',
    'potion.itIs': 'C’est {name} !',
    'potion.continue': 'Continuer',
    'potion.level': 'Niveau {n}',
    'potion.and': ' et ',
    'potion.comma': ', ',
    'potion.drop.one': '{n} goutte de {color}',
    'potion.drop.many': '{n} gouttes de {color}',
    'potion.n.1': 'une', 'potion.n.2': 'deux', 'potion.n.3': 'trois', 'potion.n.4': 'quatre', 'potion.n.5': 'cinq',

    'potion.color.red': 'rouge', 'potion.color.yellow': 'jaune', 'potion.color.blue': 'bleue',
    'potion.color.orange': 'orange', 'potion.color.purple': 'violette', 'potion.color.green': 'verte',
    'potion.color.yelloworange': 'jaune orangé', 'potion.color.redorange': 'rouge orangé',
    'potion.color.applegreen': 'vert pomme', 'potion.color.bluegreen': 'bleu-vert',
    'potion.color.raspberry': 'framboise', 'potion.color.indigo': 'indigo',
    'potion.color.pink': 'rose', 'potion.color.lightblue': 'bleu clair', 'potion.color.paleyellow': 'jaune pâle',
    'potion.color.lightgreen': 'vert clair', 'potion.color.lilac': 'lilas', 'potion.color.peach': 'pêche',
    'potion.color.darkred': 'rouge foncé', 'potion.color.darkblue': 'bleu foncé', 'potion.color.darkgreen': 'vert foncé',
    'potion.color.softgreen': 'vert tendre', 'potion.color.dustypink': 'vieux rose', 'potion.color.greyblue': 'bleu gris', 'potion.color.coral': 'corail',
    'potion.color.olive': 'kaki', 'potion.color.beige': 'beige', 'potion.color.brown': 'marron', 'potion.color.white': 'blanche', 'potion.color.black': 'noire', 'potion.color.grey': 'grise',

    'potion.name.red': 'rouge', 'potion.name.yellow': 'jaune', 'potion.name.blue': 'bleu',
    'potion.name.orange': 'orange', 'potion.name.purple': 'violet', 'potion.name.green': 'vert',
    'potion.name.yelloworange': 'jaune orangé', 'potion.name.redorange': 'rouge orangé',
    'potion.name.applegreen': 'vert pomme', 'potion.name.bluegreen': 'bleu-vert',
    'potion.name.raspberry': 'framboise', 'potion.name.indigo': 'indigo',
    'potion.name.pink': 'rose', 'potion.name.lightblue': 'bleu clair', 'potion.name.paleyellow': 'jaune pâle',
    'potion.name.lightgreen': 'vert clair', 'potion.name.lilac': 'lilas', 'potion.name.peach': 'pêche',
    'potion.name.darkred': 'rouge foncé', 'potion.name.darkblue': 'bleu foncé', 'potion.name.darkgreen': 'vert foncé',
    'potion.name.softgreen': 'vert tendre', 'potion.name.dustypink': 'vieux rose', 'potion.name.greyblue': 'bleu gris', 'potion.name.coral': 'corail',
    'potion.name.olive': 'kaki', 'potion.name.beige': 'beige', 'potion.name.brown': 'marron', 'potion.name.white': 'blanc', 'potion.name.black': 'noir', 'potion.name.grey': 'gris',
  },
  es: {
    'potion.chooseLevel': '¡Elige un nivel!',
    'potion.ask': '¡Quiero una poción {color}, por favor!',
    'potion.askRecipe': '¡Quiero una poción con {recipe}, por favor!',
    'potion.howTo': '¡Arrastra los colores al caldero y luego mezcla con la cuchara!',
    'potion.stir': 'Mezclar',
    'potion.empty': 'Vaciar el caldero',
    'potion.full': '¡El caldero está lleno! Mezcla o vacíalo.',
    'potion.success.simple': '¡Gracias! ¡Es perfecta!',
    'potion.success.mix': '¡{list} hacen {result}! ¡Gracias!',
    'potion.success.count': '¡Bravo, contaste muy bien! ¡Sale {result}!',
    'potion.wrong.1': '¡Uy! No es el color correcto. ¡Inténtalo otra vez!',
    'potion.wrong.2': '¡Ji ji, qué cosquillas! Pero no es mi color.',
    'potion.wrong.3': 'Mmm… ¡casi! ¿Probamos otra vez?',
    'potion.hint': '¡Mira los colores que brillan!',
    'potion.hintEmpty': '¡Vacía el caldero y mira los colores que brillan!',
    'potion.hintCount': '¡Cuenta bien las gotas! Mira los puntitos.',
    'potion.hintMore': '¡Casi! ¡Añade un poco más de {color}!',
    'potion.levelDone': '¡Bravo! ¡Terminaste el nivel!',
    'potion.freeIntro': '¡El laboratorio es tuyo! ¡Mezcla todos los colores que quieras!',
    'potion.itIs': '¡Es {name}!',
    'potion.continue': 'Seguir',
    'potion.level': 'Nivel {n}',
    'potion.and': ' y ',
    'potion.comma': ', ',
    'potion.drop.one': '{n} gota de {color}',
    'potion.drop.many': '{n} gotas de {color}',
    'potion.n.1': 'una', 'potion.n.2': 'dos', 'potion.n.3': 'tres', 'potion.n.4': 'cuatro', 'potion.n.5': 'cinco',

    'potion.color.red': 'roja', 'potion.color.yellow': 'amarilla', 'potion.color.blue': 'azul',
    'potion.color.orange': 'naranja', 'potion.color.purple': 'morada', 'potion.color.green': 'verde',
    'potion.color.yelloworange': 'amarillo anaranjado', 'potion.color.redorange': 'rojo anaranjado',
    'potion.color.applegreen': 'verde manzana', 'potion.color.bluegreen': 'azul verdoso',
    'potion.color.raspberry': 'frambuesa', 'potion.color.indigo': 'índigo',
    'potion.color.pink': 'rosa', 'potion.color.lightblue': 'celeste', 'potion.color.paleyellow': 'amarillo pálido',
    'potion.color.lightgreen': 'verde claro', 'potion.color.lilac': 'lila', 'potion.color.peach': 'durazno',
    'potion.color.darkred': 'rojo oscuro', 'potion.color.darkblue': 'azul oscuro', 'potion.color.darkgreen': 'verde oscuro',
    'potion.color.softgreen': 'verde lima', 'potion.color.dustypink': 'rosa viejo', 'potion.color.greyblue': 'azul grisáceo', 'potion.color.coral': 'coral',
    'potion.color.olive': 'verde oliva', 'potion.color.beige': 'beige', 'potion.color.brown': 'marrón', 'potion.color.white': 'blanca', 'potion.color.black': 'negra', 'potion.color.grey': 'gris',

    'potion.name.red': 'rojo', 'potion.name.yellow': 'amarillo', 'potion.name.blue': 'azul',
    'potion.name.orange': 'naranja', 'potion.name.purple': 'morado', 'potion.name.green': 'verde',
    'potion.name.yelloworange': 'amarillo anaranjado', 'potion.name.redorange': 'rojo anaranjado',
    'potion.name.applegreen': 'verde manzana', 'potion.name.bluegreen': 'azul verdoso',
    'potion.name.raspberry': 'frambuesa', 'potion.name.indigo': 'índigo',
    'potion.name.pink': 'rosa', 'potion.name.lightblue': 'celeste', 'potion.name.paleyellow': 'amarillo pálido',
    'potion.name.lightgreen': 'verde claro', 'potion.name.lilac': 'lila', 'potion.name.peach': 'durazno',
    'potion.name.darkred': 'rojo oscuro', 'potion.name.darkblue': 'azul oscuro', 'potion.name.darkgreen': 'verde oscuro',
    'potion.name.softgreen': 'verde lima', 'potion.name.dustypink': 'rosa viejo', 'potion.name.greyblue': 'azul grisáceo', 'potion.name.coral': 'coral',
    'potion.name.olive': 'verde oliva', 'potion.name.beige': 'beige', 'potion.name.brown': 'marrón', 'potion.name.white': 'blanco', 'potion.name.black': 'negro', 'potion.name.grey': 'gris',
  },
  en: {
    'potion.chooseLevel': 'Pick a level!',
    'potion.ask': 'I’d like a {color} potion, please!',
    'potion.askRecipe': 'I’d like a potion with {recipe}, please!',
    'potion.howTo': 'Drag the colours into the cauldron, then stir with the spoon!',
    'potion.stir': 'Stir',
    'potion.empty': 'Empty the cauldron',
    'potion.full': 'The cauldron is full! Stir it or empty it.',
    'potion.success.simple': 'Thank you! It’s perfect!',
    'potion.success.mix': '{list} make {result}! Thank you!',
    'potion.success.count': 'Well counted! That makes {result}!',
    'potion.wrong.1': 'Oops! That’s not the right colour. Try again!',
    'potion.wrong.2': 'Hee hee, that tickles! But it’s not my colour.',
    'potion.wrong.3': 'Hmm… not quite! Shall we try again?',
    'potion.hint': 'Look at the colours that sparkle!',
    'potion.hintEmpty': 'Empty the cauldron, and look at the colours that sparkle!',
    'potion.hintCount': 'Count the drops carefully! Look at the dots.',
    'potion.hintMore': 'Almost! Add a little more {color}!',
    'potion.levelDone': 'Well done! You finished the level!',
    'potion.freeIntro': 'The lab is yours! Mix any colours you like!',
    'potion.itIs': 'It’s {name}!',
    'potion.continue': 'Continue',
    'potion.level': 'Level {n}',
    'potion.and': ' and ',
    'potion.comma': ', ',
    'potion.drop.one': '{n} drop of {color}',
    'potion.drop.many': '{n} drops of {color}',
    'potion.n.1': 'one', 'potion.n.2': 'two', 'potion.n.3': 'three', 'potion.n.4': 'four', 'potion.n.5': 'five',

    'potion.color.red': 'red', 'potion.color.yellow': 'yellow', 'potion.color.blue': 'blue',
    'potion.color.orange': 'orange', 'potion.color.purple': 'purple', 'potion.color.green': 'green',
    'potion.color.yelloworange': 'yellow-orange', 'potion.color.redorange': 'red-orange',
    'potion.color.applegreen': 'apple green', 'potion.color.bluegreen': 'blue-green',
    'potion.color.raspberry': 'raspberry', 'potion.color.indigo': 'indigo',
    'potion.color.pink': 'pink', 'potion.color.lightblue': 'light blue', 'potion.color.paleyellow': 'pale yellow',
    'potion.color.lightgreen': 'light green', 'potion.color.lilac': 'lilac', 'potion.color.peach': 'peach',
    'potion.color.darkred': 'dark red', 'potion.color.darkblue': 'dark blue', 'potion.color.darkgreen': 'dark green',
    'potion.color.softgreen': 'lime green', 'potion.color.dustypink': 'dusty pink', 'potion.color.greyblue': 'grey-blue', 'potion.color.coral': 'coral',
    'potion.color.olive': 'olive', 'potion.color.beige': 'beige', 'potion.color.brown': 'brown', 'potion.color.white': 'white', 'potion.color.black': 'black', 'potion.color.grey': 'grey',

    'potion.name.red': 'red', 'potion.name.yellow': 'yellow', 'potion.name.blue': 'blue',
    'potion.name.orange': 'orange', 'potion.name.purple': 'purple', 'potion.name.green': 'green',
    'potion.name.yelloworange': 'yellow-orange', 'potion.name.redorange': 'red-orange',
    'potion.name.applegreen': 'apple green', 'potion.name.bluegreen': 'blue-green',
    'potion.name.raspberry': 'raspberry', 'potion.name.indigo': 'indigo',
    'potion.name.pink': 'pink', 'potion.name.lightblue': 'light blue', 'potion.name.paleyellow': 'pale yellow',
    'potion.name.lightgreen': 'light green', 'potion.name.lilac': 'lilac', 'potion.name.peach': 'peach',
    'potion.name.darkred': 'dark red', 'potion.name.darkblue': 'dark blue', 'potion.name.darkgreen': 'dark green',
    'potion.name.softgreen': 'lime green', 'potion.name.dustypink': 'dusty pink', 'potion.name.greyblue': 'grey-blue', 'potion.name.coral': 'coral',
    'potion.name.olive': 'olive', 'potion.name.beige': 'beige', 'potion.name.brown': 'brown', 'potion.name.white': 'white', 'potion.name.black': 'black', 'potion.name.grey': 'grey',
  },
};
