// Everything "Le Marché" says, in fr / es / en.
// Keys ending in .one / .other are the singular and plural sentence for an amount —
// plural.js picks the right one (never glue "franc" + "s" together).
// Keys ending in .1 .2 .3 are variants picked at random.
export default {
  fr: {
    'market.chooseLevel': 'Choisis un niveau !',
    'market.level': 'Niveau {n}',
    'market.howTo': 'Touche une pièce de ton porte-monnaie pour la poser sur le comptoir.',
    'market.intro.two': 'Nouvelle pièce ! Celle-ci vaut 2 francs.',
    'market.intro.five': 'Nouvelle pièce ! Celle-ci vaut 5 francs.',
    'market.intro.basket': 'Maintenant, les clients achètent deux choses !',
    'market.intro.seller': 'C’est toi la marchande ! Rends la monnaie au client.',
    'market.intro.free': 'Le marché est à vous ! L’une vend, l’autre achète.',
    'market.want.apple': 'Bonjour ! Je voudrais une pomme.',
    'market.want.pear': 'Bonjour ! Je voudrais une poire.',
    'market.want.banana': 'Bonjour ! Je voudrais une banane.',
    'market.want.carrot': 'Bonjour ! Je voudrais une carotte.',
    'market.want.bread': 'Bonjour ! Je voudrais un pain.',
    'market.want.croissant': 'Bonjour ! Je voudrais un croissant.',
    'market.want.ball': 'Bonjour ! Je voudrais un ballon.',
    'market.want.boat': 'Bonjour ! Je voudrais un petit bateau.',
    'market.price.one': 'Ça coûte {n} franc.',
    'market.price.other': 'Ça coûte {n} francs.',
    'market.coinValue.one': 'Cette pièce vaut {n} franc.',
    'market.coinValue.other': 'Cette pièce vaut {n} francs.',
    'market.trayFull': 'Le comptoir est plein !',
    'market.tray': 'Le comptoir',
    'market.stack.one': 'Pièces de {n} franc : {count}',
    'market.stack.other': 'Pièces de {n} francs : {count}',
    'market.coin.one': '{n} franc',
    'market.coin.other': '{n} francs',
  },
  es: {
    'market.chooseLevel': '¡Elige un nivel!',
    'market.level': 'Nivel {n}',
    'market.howTo': 'Toca una moneda de tu monedero para ponerla en el mostrador.',
    'market.intro.two': '¡Moneda nueva! Esta vale 2 francos.',
    'market.intro.five': '¡Moneda nueva! Esta vale 5 francos.',
    'market.intro.basket': '¡Ahora los clientes compran dos cosas!',
    'market.intro.seller': '¡Ahora tú eres la vendedora! Devuelve el cambio al cliente.',
    'market.intro.free': '¡El mercado es vuestro! Una vende y la otra compra.',
    'market.want.apple': '¡Hola! Quisiera una manzana.',
    'market.want.pear': '¡Hola! Quisiera una pera.',
    'market.want.banana': '¡Hola! Quisiera un plátano.',
    'market.want.carrot': '¡Hola! Quisiera una zanahoria.',
    'market.want.bread': '¡Hola! Quisiera un pan.',
    'market.want.croissant': '¡Hola! Quisiera un cruasán.',
    'market.want.ball': '¡Hola! Quisiera una pelota.',
    'market.want.boat': '¡Hola! Quisiera un barquito.',
    'market.price.one': 'Cuesta {n} franco.',
    'market.price.other': 'Cuesta {n} francos.',
    'market.coinValue.one': 'Esta moneda vale {n} franco.',
    'market.coinValue.other': 'Esta moneda vale {n} francos.',
    'market.trayFull': '¡El mostrador está lleno!',
    'market.tray': 'El mostrador',
    'market.stack.one': 'Monedas de {n} franco: {count}',
    'market.stack.other': 'Monedas de {n} francos: {count}',
    'market.coin.one': '{n} franco',
    'market.coin.other': '{n} francos',
  },
  en: {
    'market.chooseLevel': 'Choose a level!',
    'market.level': 'Level {n}',
    'market.howTo': 'Touch a coin in your purse to put it on the counter.',
    'market.intro.two': 'A new coin! This one is worth 2 francs.',
    'market.intro.five': 'A new coin! This one is worth 5 francs.',
    'market.intro.basket': 'Now the customers buy two things!',
    'market.intro.seller': 'Now you are the seller! Give the customer the change.',
    'market.intro.free': 'The market is yours! One of you sells, the other buys.',
    'market.want.apple': 'Hello! I’d like an apple.',
    'market.want.pear': 'Hello! I’d like a pear.',
    'market.want.banana': 'Hello! I’d like a banana.',
    'market.want.carrot': 'Hello! I’d like a carrot.',
    'market.want.bread': 'Hello! I’d like a loaf of bread.',
    'market.want.croissant': 'Hello! I’d like a croissant.',
    'market.want.ball': 'Hello! I’d like a ball.',
    'market.want.boat': 'Hello! I’d like a toy boat.',
    'market.price.one': 'It costs {n} franc.',
    'market.price.other': 'It costs {n} francs.',
    'market.coinValue.one': 'This coin is worth {n} franc.',
    'market.coinValue.other': 'This coin is worth {n} francs.',
    'market.trayFull': 'The counter is full!',
    'market.tray': 'The counter',
    'market.stack.one': '{n}-franc coins: {count}',
    'market.stack.other': '{n}-franc coins: {count}',
    'market.coin.one': '{n} franc',
    'market.coin.other': '{n} francs',
  },
};
