// Everything "Le Marché" says, in fr / es / en.
// Keys ending in .one / .other are the singular and plural sentence for an amount —
// plural.js picks the right one (never glue "franc" + "s" together).
// Keys ending in .1 .2 .3 are variants picked at random.
export default {
  fr: {
    'market.chooseLevel': 'Choisis un niveau !',
    'market.level': 'Niveau {n}',
    'market.howTo': 'Glisse des pièces de ton porte-monnaie sur le comptoir, puis appuie sur la main verte pour payer.',
    'market.intro.two': 'Nouvelle pièce ! Celle-ci vaut 2 francs.',
    'market.intro.five': 'Nouvelle pièce ! Celle-ci vaut 5 francs.',
    'market.intro.basket': 'Maintenant, les clients achètent deux choses !',
    'market.intro.seller': 'C’est toi la marchande ! Rends la monnaie au client.',
    'market.intro.free': 'Le marché est à vous ! L’une vend, l’autre achète.',
    'market.want.apple': 'Bonjour ! Je voudrais une pomme.',
    'market.want.pear': 'Bonjour ! Je voudrais une poire.',
    'market.want.banana': 'Bonjour ! Je voudrais une banane.',
    'market.want.carrot': 'Bonjour ! Je voudrais une carotte.',
    'market.want.bread': 'Bonjour ! Je voudrais un pain.',
    'market.want.croissant': 'Bonjour ! Je voudrais un croissant.',
    'market.want.ball': 'Bonjour ! Je voudrais un ballon.',
    'market.want.boat': 'Bonjour ! Je voudrais un petit bateau.',
    'market.price.one': 'Ça coûte {n} franc.',
    'market.price.other': 'Ça coûte {n} francs.',
    'market.coinValue.one': 'Cette pièce vaut {n} franc.',
    'market.coinValue.other': 'Cette pièce vaut {n} francs.',
    'market.trayFull': 'Le comptoir est plein !',
    'market.tray': 'Le comptoir',
    'market.stack.one': 'Pièces de {n} franc : {count}',
    'market.stack.other': 'Pièces de {n} francs : {count}',
    'market.coin.one': '{n} franc',
    'market.coin.other': '{n} francs',
    'market.pay': 'Payer',
    'market.emptyTray': 'Pose d’abord des pièces sur le comptoir !',
    'market.more.one': 'Encore {n} franc, s’il te plaît !',
    'market.more.other': 'Encore {n} francs, s’il te plaît !',
    'market.tooMuch.one': 'Oh, c’est {n} franc de trop ! Je te le rends.',
    'market.tooMuch.other': 'Oh, c’est {n} francs de trop ! Je te les rends.',
    'market.hintTarget': 'Regarde les ronds rouges sur le comptoir : remplis-les tous avec tes pièces !',
    'market.hintCoins': 'Essaie avec les pièces qui bougent !',
    'market.thanks.1': 'Merci beaucoup ! Au revoir !',
    'market.thanks.2': 'Parfait, le compte est bon ! Merci !',
    'market.thanks.3': 'Super ! Merci et à bientôt !',
    'market.bonus': 'Avec le moins de pièces possible ! Une étoile en plus !',
    'market.fewer': 'Merci ! Et avec moins de pièces, tu y arriverais ?',
    'market.levelDone': 'Bravo ! Tu as fini le niveau !',
    'market.continue': 'Continuer',
  },
  es: {
    'market.chooseLevel': '¡Elige un nivel!',
    'market.level': 'Nivel {n}',
    'market.howTo': 'Arrastra monedas de tu monedero al mostrador y luego pulsa la mano verde para pagar.',
    'market.intro.two': '¡Moneda nueva! Esta vale 2 francos.',
    'market.intro.five': '¡Moneda nueva! Esta vale 5 francos.',
    'market.intro.basket': '¡Ahora los clientes compran dos cosas!',
    'market.intro.seller': '¡Ahora tú eres la vendedora! Devuelve el cambio al cliente.',
    'market.intro.free': '¡El mercado es vuestro! Una vende y la otra compra.',
    'market.want.apple': '¡Hola! Quisiera una manzana.',
    'market.want.pear': '¡Hola! Quisiera una pera.',
    'market.want.banana': '¡Hola! Quisiera un plátano.',
    'market.want.carrot': '¡Hola! Quisiera una zanahoria.',
    'market.want.bread': '¡Hola! Quisiera un pan.',
    'market.want.croissant': '¡Hola! Quisiera un cruasán.',
    'market.want.ball': '¡Hola! Quisiera una pelota.',
    'market.want.boat': '¡Hola! Quisiera un barquito.',
    'market.price.one': 'Cuesta {n} franco.',
    'market.price.other': 'Cuesta {n} francos.',
    'market.coinValue.one': 'Esta moneda vale {n} franco.',
    'market.coinValue.other': 'Esta moneda vale {n} francos.',
    'market.trayFull': '¡El mostrador está lleno!',
    'market.tray': 'El mostrador',
    'market.stack.one': 'Monedas de {n} franco: {count}',
    'market.stack.other': 'Monedas de {n} francos: {count}',
    'market.coin.one': '{n} franco',
    'market.coin.other': '{n} francos',
    'market.pay': 'Pagar',
    'market.emptyTray': '¡Primero pon monedas en el mostrador!',
    'market.more.one': 'Falta {n} franco, por favor.',
    'market.more.other': 'Faltan {n} francos, por favor.',
    'market.tooMuch.one': '¡Oh, es {n} franco de más! Te lo devuelvo.',
    'market.tooMuch.other': '¡Oh, son {n} francos de más! Te los devuelvo.',
    'market.hintTarget': 'Mira los círculos rojos del mostrador: ¡llénalos todos con tus monedas!',
    'market.hintCoins': '¡Prueba con las monedas que se mueven!',
    'market.thanks.1': '¡Muchas gracias! ¡Adiós!',
    'market.thanks.2': '¡Perfecto, la cuenta está bien! ¡Gracias!',
    'market.thanks.3': '¡Genial! ¡Gracias y hasta pronto!',
    'market.bonus': '¡Con el menor número de monedas! ¡Una estrella extra!',
    'market.fewer': '¡Gracias! ¿Y podrías hacerlo con menos monedas?',
    'market.levelDone': '¡Bravo! ¡Has terminado el nivel!',
    'market.continue': 'Continuar',
  },
  en: {
    'market.chooseLevel': 'Choose a level!',
    'market.level': 'Level {n}',
    'market.howTo': 'Drag coins from your purse onto the counter, then press the green hand to pay.',
    'market.intro.two': 'A new coin! This one is worth 2 francs.',
    'market.intro.five': 'A new coin! This one is worth 5 francs.',
    'market.intro.basket': 'Now the customers buy two things!',
    'market.intro.seller': 'Now you are the seller! Give the customer the change.',
    'market.intro.free': 'The market is yours! One of you sells, the other buys.',
    'market.want.apple': 'Hello! I’d like an apple.',
    'market.want.pear': 'Hello! I’d like a pear.',
    'market.want.banana': 'Hello! I’d like a banana.',
    'market.want.carrot': 'Hello! I’d like a carrot.',
    'market.want.bread': 'Hello! I’d like a loaf of bread.',
    'market.want.croissant': 'Hello! I’d like a croissant.',
    'market.want.ball': 'Hello! I’d like a ball.',
    'market.want.boat': 'Hello! I’d like a toy boat.',
    'market.price.one': 'It costs {n} franc.',
    'market.price.other': 'It costs {n} francs.',
    'market.coinValue.one': 'This coin is worth {n} franc.',
    'market.coinValue.other': 'This coin is worth {n} francs.',
    'market.trayFull': 'The counter is full!',
    'market.tray': 'The counter',
    'market.stack.one': '{n}-franc coins: {count}',
    'market.stack.other': '{n}-franc coins: {count}',
    'market.coin.one': '{n} franc',
    'market.coin.other': '{n} francs',
    'market.pay': 'Pay',
    'market.emptyTray': 'Put some coins on the counter first!',
    'market.more.one': 'I need {n} more franc, please!',
    'market.more.other': 'I need {n} more francs, please!',
    'market.tooMuch.one': 'Oh, that’s {n} franc too much! Here it is back.',
    'market.tooMuch.other': 'Oh, that’s {n} francs too much! Here they are back.',
    'market.hintTarget': 'Look at the red circles on the counter: fill them all with your coins!',
    'market.hintCoins': 'Try the coins that are wiggling!',
    'market.thanks.1': 'Thank you very much! Goodbye!',
    'market.thanks.2': 'Perfect, that’s exactly right! Thank you!',
    'market.thanks.3': 'Great! Thanks, see you soon!',
    'market.bonus': 'With the fewest coins possible! A bonus star!',
    'market.fewer': 'Thank you! Could you do it with fewer coins?',
    'market.levelDone': 'Well done! You finished the level!',
    'market.continue': 'Continue',
  },
};
