// Everything "Le Marché" says, in fr / es / en.
// Keys ending in .one / .other are the singular and plural sentence for an amount —
// plural.js picks the right one (never glue "franc" + "s" together).
// Keys ending in .1 .2 .3 are variants picked at random.
export default {
  fr: {
    'market.chooseLevel': 'Choisis un niveau !',
    'market.level': 'Niveau {n}',
    'market.howTo': 'Glisse des pièces de ton porte-monnaie sur le comptoir, puis appuie sur la main verte pour payer.',
    'market.intro.two': 'Nouvelle pièce ! Celle-ci vaut 2 francs.',
    'market.intro.five': 'Nouvelle pièce ! Celle-ci vaut 5 francs.',
    'market.intro.basket': 'Maintenant, tu achètes deux choses : additionne les deux prix !',
    'market.intro.seller': 'C’est toi la marchande ! Rends la monnaie au client.',
    'market.intro.free': 'Le marché est à vous ! L’une vend, l’autre achète.',
    'market.costs.apple.one': 'La pomme coûte {n} franc.',
    'market.costs.apple.other': 'La pomme coûte {n} francs.',
    'market.costs.pear.one': 'La poire coûte {n} franc.',
    'market.costs.pear.other': 'La poire coûte {n} francs.',
    'market.costs.banana.one': 'La banane coûte {n} franc.',
    'market.costs.banana.other': 'La banane coûte {n} francs.',
    'market.costs.carrot.one': 'La carotte coûte {n} franc.',
    'market.costs.carrot.other': 'La carotte coûte {n} francs.',
    'market.costs.bread.one': 'Le pain coûte {n} franc.',
    'market.costs.bread.other': 'Le pain coûte {n} francs.',
    'market.costs.croissant.one': 'Le croissant coûte {n} franc.',
    'market.costs.croissant.other': 'Le croissant coûte {n} francs.',
    'market.costs.ball.one': 'Le ballon coûte {n} franc.',
    'market.costs.ball.other': 'Le ballon coûte {n} francs.',
    'market.costs.boat.one': 'Le petit bateau coûte {n} franc.',
    'market.costs.boat.other': 'Le petit bateau coûte {n} francs.',
    'market.coinValue.one': 'Cette pièce vaut {n} franc.',
    'market.coinValue.other': 'Cette pièce vaut {n} francs.',
    'market.trayFull': 'Le comptoir est plein !',
    'market.tray': 'Le comptoir',
    'market.stack.one': 'Pièces de {n} franc : {count}',
    'market.stack.other': 'Pièces de {n} francs : {count}',
    'market.coin.one': '{n} franc',
    'market.coin.other': '{n} francs',
    'market.pay': 'Payer',
    'market.emptyTray': 'Pose d’abord des pièces sur le comptoir !',
    'market.more.one': 'Encore {n} franc, s’il te plaît !',
    'market.more.other': 'Encore {n} francs, s’il te plaît !',
    'market.tooMuch.one': 'Tu m’as donné {n} franc de trop, je te le rends !',
    'market.tooMuch.other': 'Tu m’as donné {n} francs de trop, je te les rends !',
    'market.hintTarget': 'Regarde les ronds rouges sur le comptoir : remplis-les tous avec tes pièces !',
    'market.hintCoins': 'Essaie avec les pièces qui bougent !',
    'market.thanks.1': 'Merci beaucoup ! Au revoir !',
    'market.thanks.2': 'Parfait, le compte est bon ! Merci !',
    'market.thanks.3': 'Super ! Merci et à bientôt !',
    'market.bonus': 'Avec le moins de pièces possible ! Une étoile en plus !',
    'market.fewer': 'Merci ! Et avec moins de pièces, tu y arriverais ?',
    'market.levelDone': 'Bravo ! Tu as fini le niveau !',
    'market.continue': 'Continuer',
    'market.hello': 'Bonjour !',
    'market.inTotal': 'Ça fait combien en tout ?',
    'market.pays.one': 'Voici {n} franc. Tu me rends la monnaie ?',
    'market.pays.other': 'Voici {n} francs. Tu me rends la monnaie ?',
    'market.changeTooMuch.one': 'Oh, tu m’as rendu {n} franc de trop ! Je te le redonne.',
    'market.changeTooMuch.other': 'Oh, tu m’as rendu {n} francs de trop ! Je te les redonne.',
    'market.hintChange': 'Les points du prix sont déjà là : ajoute des pièces jusqu’à remplir les ronds rouges !',
    'market.giveChange': 'Rendre la monnaie',
    'market.free.toSeller': 'À la vendeuse ! Touche un prix pour le changer, puis les flèches pour passer à l’acheteuse.',
    'market.free.toBuyer': 'À l’acheteuse ! Touche ce que tu veux acheter, puis paie avec tes pièces.',
    'market.free.turn': 'Changer de rôle',
    'market.free.pickFirst': 'Choisis d’abord quelque chose à acheter !',
    'market.free.basketFull': 'Le panier est plein : pas plus de 20 francs !',
    'market.free.over.one': 'C’est {n} franc de trop. Vendeuse, rends la monnaie !',
    'market.free.over.other': 'C’est {n} francs de trop. Vendeuse, rends la monnaie !',
    'market.free.changeOver.one': 'Oups, {n} franc de trop ! Reprends-le.',
    'market.free.changeOver.other': 'Oups, {n} francs de trop ! Reprends-les.',
    'market.free.sold': 'Vendu ! Merci et à bientôt !',
  },
  es: {
    'market.chooseLevel': '¡Elige un nivel!',
    'market.level': 'Nivel {n}',
    'market.howTo': 'Arrastra monedas de tu monedero al mostrador y luego pulsa la mano verde para pagar.',
    'market.intro.two': '¡Moneda nueva! Esta vale 2 francos.',
    'market.intro.five': '¡Moneda nueva! Esta vale 5 francos.',
    'market.intro.basket': 'Ahora compras dos cosas: ¡suma los dos precios!',
    'market.intro.seller': '¡Ahora tú eres la vendedora! Devuelve el cambio al cliente.',
    'market.intro.free': '¡El mercado es vuestro! Una vende y la otra compra.',
    'market.costs.apple.one': 'La manzana cuesta {n} franco.',
    'market.costs.apple.other': 'La manzana cuesta {n} francos.',
    'market.costs.pear.one': 'La pera cuesta {n} franco.',
    'market.costs.pear.other': 'La pera cuesta {n} francos.',
    'market.costs.banana.one': 'El plátano cuesta {n} franco.',
    'market.costs.banana.other': 'El plátano cuesta {n} francos.',
    'market.costs.carrot.one': 'La zanahoria cuesta {n} franco.',
    'market.costs.carrot.other': 'La zanahoria cuesta {n} francos.',
    'market.costs.bread.one': 'El pan cuesta {n} franco.',
    'market.costs.bread.other': 'El pan cuesta {n} francos.',
    'market.costs.croissant.one': 'El cruasán cuesta {n} franco.',
    'market.costs.croissant.other': 'El cruasán cuesta {n} francos.',
    'market.costs.ball.one': 'La pelota cuesta {n} franco.',
    'market.costs.ball.other': 'La pelota cuesta {n} francos.',
    'market.costs.boat.one': 'El barquito cuesta {n} franco.',
    'market.costs.boat.other': 'El barquito cuesta {n} francos.',
    'market.coinValue.one': 'Esta moneda vale {n} franco.',
    'market.coinValue.other': 'Esta moneda vale {n} francos.',
    'market.trayFull': '¡El mostrador está lleno!',
    'market.tray': 'El mostrador',
    'market.stack.one': 'Monedas de {n} franco: {count}',
    'market.stack.other': 'Monedas de {n} francos: {count}',
    'market.coin.one': '{n} franco',
    'market.coin.other': '{n} francos',
    'market.pay': 'Pagar',
    'market.emptyTray': '¡Primero pon monedas en el mostrador!',
    'market.more.one': 'Falta {n} franco, por favor.',
    'market.more.other': 'Faltan {n} francos, por favor.',
    'market.tooMuch.one': '¡Me has dado {n} franco de más, te lo devuelvo!',
    'market.tooMuch.other': '¡Me has dado {n} francos de más, te los devuelvo!',
    'market.hintTarget': 'Mira los círculos rojos del mostrador: ¡llénalos todos con tus monedas!',
    'market.hintCoins': '¡Prueba con las monedas que se mueven!',
    'market.thanks.1': '¡Muchas gracias! ¡Adiós!',
    'market.thanks.2': '¡Perfecto, la cuenta está bien! ¡Gracias!',
    'market.thanks.3': '¡Genial! ¡Gracias y hasta pronto!',
    'market.bonus': '¡Con el menor número de monedas! ¡Una estrella extra!',
    'market.fewer': '¡Gracias! ¿Y podrías hacerlo con menos monedas?',
    'market.levelDone': '¡Bravo! ¡Has terminado el nivel!',
    'market.continue': 'Continuar',
    'market.hello': '¡Hola!',
    'market.inTotal': '¿Cuánto es en total?',
    'market.pays.one': 'Aquí tienes {n} franco. ¿Me das el cambio?',
    'market.pays.other': 'Aquí tienes {n} francos. ¿Me das el cambio?',
    'market.changeTooMuch.one': '¡Oh, me has devuelto {n} franco de más! Te lo devuelvo.',
    'market.changeTooMuch.other': '¡Oh, me has devuelto {n} francos de más! Te los devuelvo.',
    'market.hintChange': 'Los puntos del precio ya están: ¡añade monedas hasta llenar los círculos rojos!',
    'market.giveChange': 'Dar el cambio',
    'market.free.toSeller': '¡Turno de la vendedora! Toca un precio para cambiarlo y luego las flechas para pasar a la compradora.',
    'market.free.toBuyer': '¡Turno de la compradora! Toca lo que quieres comprar y paga con tus monedas.',
    'market.free.turn': 'Cambiar de papel',
    'market.free.pickFirst': '¡Primero elige algo para comprar!',
    'market.free.basketFull': '¡La cesta está llena: no más de 20 francos!',
    'market.free.over.one': 'Es {n} franco de más. ¡Vendedora, devuelve el cambio!',
    'market.free.over.other': 'Son {n} francos de más. ¡Vendedora, devuelve el cambio!',
    'market.free.changeOver.one': '¡Uy, {n} franco de más! Quítalo.',
    'market.free.changeOver.other': '¡Uy, {n} francos de más! Quítalos.',
    'market.free.sold': '¡Vendido! ¡Gracias y hasta pronto!',
  },
  en: {
    'market.chooseLevel': 'Choose a level!',
    'market.level': 'Level {n}',
    'market.howTo': 'Drag coins from your purse onto the counter, then press the green hand to pay.',
    'market.intro.two': 'A new coin! This one is worth 2 francs.',
    'market.intro.five': 'A new coin! This one is worth 5 francs.',
    'market.intro.basket': 'Now you buy two things: add the two prices together!',
    'market.intro.seller': 'Now you are the seller! Give the customer the change.',
    'market.intro.free': 'The market is yours! One of you sells, the other buys.',
    'market.costs.apple.one': 'The apple costs {n} franc.',
    'market.costs.apple.other': 'The apple costs {n} francs.',
    'market.costs.pear.one': 'The pear costs {n} franc.',
    'market.costs.pear.other': 'The pear costs {n} francs.',
    'market.costs.banana.one': 'The banana costs {n} franc.',
    'market.costs.banana.other': 'The banana costs {n} francs.',
    'market.costs.carrot.one': 'The carrot costs {n} franc.',
    'market.costs.carrot.other': 'The carrot costs {n} francs.',
    'market.costs.bread.one': 'The bread costs {n} franc.',
    'market.costs.bread.other': 'The bread costs {n} francs.',
    'market.costs.croissant.one': 'The croissant costs {n} franc.',
    'market.costs.croissant.other': 'The croissant costs {n} francs.',
    'market.costs.ball.one': 'The ball costs {n} franc.',
    'market.costs.ball.other': 'The ball costs {n} francs.',
    'market.costs.boat.one': 'The toy boat costs {n} franc.',
    'market.costs.boat.other': 'The toy boat costs {n} francs.',
    'market.coinValue.one': 'This coin is worth {n} franc.',
    'market.coinValue.other': 'This coin is worth {n} francs.',
    'market.trayFull': 'The counter is full!',
    'market.tray': 'The counter',
    'market.stack.one': '{n}-franc coins: {count}',
    'market.stack.other': '{n}-franc coins: {count}',
    'market.coin.one': '{n} franc',
    'market.coin.other': '{n} francs',
    'market.pay': 'Pay',
    'market.emptyTray': 'Put some coins on the counter first!',
    'market.more.one': 'I need {n} more franc, please!',
    'market.more.other': 'I need {n} more francs, please!',
    'market.tooMuch.one': 'You gave me {n} franc too much, here it is back!',
    'market.tooMuch.other': 'You gave me {n} francs too much, here they are back!',
    'market.hintTarget': 'Look at the red circles on the counter: fill them all with your coins!',
    'market.hintCoins': 'Try the coins that are wiggling!',
    'market.thanks.1': 'Thank you very much! Goodbye!',
    'market.thanks.2': 'Perfect, that’s exactly right! Thank you!',
    'market.thanks.3': 'Great! Thanks, see you soon!',
    'market.bonus': 'With the fewest coins possible! A bonus star!',
    'market.fewer': 'Thank you! Could you do it with fewer coins?',
    'market.levelDone': 'Well done! You finished the level!',
    'market.continue': 'Continue',
    'market.hello': 'Hello!',
    'market.inTotal': 'How much is that altogether?',
    'market.pays.one': 'Here is {n} franc. Can I have my change?',
    'market.pays.other': 'Here are {n} francs. Can I have my change?',
    'market.changeTooMuch.one': 'Oh, you gave me {n} franc too much! Here it is back.',
    'market.changeTooMuch.other': 'Oh, you gave me {n} francs too much! Here they are back.',
    'market.hintChange': 'The price dots are already there: add coins until the red circles are full!',
    'market.giveChange': 'Give the change',
    'market.free.toSeller': 'Seller’s turn! Touch a price to change it, then the arrows to pass to the buyer.',
    'market.free.toBuyer': 'Buyer’s turn! Touch what you want to buy, then pay with your coins.',
    'market.free.turn': 'Switch roles',
    'market.free.pickFirst': 'First choose something to buy!',
    'market.free.basketFull': 'The basket is full: no more than 20 francs!',
    'market.free.over.one': 'That’s {n} franc too much. Seller, give the change!',
    'market.free.over.other': 'That’s {n} francs too much. Seller, give the change!',
    'market.free.changeOver.one': 'Oops, {n} franc too much! Take it back.',
    'market.free.changeOver.other': 'Oops, {n} francs too much! Take them back.',
    'market.free.sold': 'Sold! Thank you, see you soon!',
  },
};
