// Everything "Robot Codeur" says, in fr / es / en.
// Lines ending in .1 .2 .3 are variants picked at random, so the robot doesn't
// always say the same thing.
export default {
  fr: {
    'robot.chooseLevel': 'Choisis un niveau !',
    'robot.ask.1': 'Aide le robot à retourner à sa station !',
    'robot.ask.2': 'Le robot a besoin de recharger ses piles ! Montre-lui le chemin.',
    'robot.ask.3': 'Bip bip ! Où est ma station ? Programme-moi !',
    'robot.howTo': 'Glisse les flèches dans la bande, puis appuie sur le bouton vert !',
    'robot.run': 'Lancer le programme',
    'robot.step': 'Une étape',
    'robot.clear': 'Tout effacer',
    'robot.card.up': 'En haut', 'robot.card.down': 'En bas', 'robot.card.left': 'À gauche', 'robot.card.right': 'À droite',
    'robot.bumpRock.1': 'Bong ! Un rocher ! Un petit bug à réparer : regarde la carte orange.',
    'robot.bumpRock.2': 'Aïe, mon nez de robot ! Il y a un bug sur la carte orange.',
    'robot.bumpEdge.1': 'Oh là là, le bord du monde ! Regarde la carte orange.',
    'robot.bumpEdge.2': 'Stop ! Je ne peux pas sortir de la grille. Répare la carte orange !',
    'robot.short': 'Il manque des flèches pour arriver à la station ! Ajoute des cartes.',
    'robot.stars': 'Tu as oublié une étoile ! Va la chercher avant la station.',
    'robot.empty': 'Mets d’abord des flèches dans la bande !',
    'robot.full': 'La bande est pleine !',
    'robot.hintNext': 'Regarde la case qui brille : c’est là qu’il faut aller !',
    'robot.hintPath': 'Suis les petits pas jusqu’à la station !',
    'robot.success.1': 'Bzzz… Rechargé ! Merci !',
    'robot.success.2': 'Bip bip ! Je suis arrivé ! Super programme !',
    'robot.success.3': 'Bravo, programmeuse ! Mes piles sont pleines !',
    'robot.levelDone': 'Bravo ! Tu as fini le niveau !',
    'robot.continue': 'Continuer',
    'robot.level': 'Niveau {n}',
    'robot.intro.stars': 'Ramasse l’étoile en chemin, puis va à la station !',
    'robot.intro.repeat': 'Nouvelle carte : Répéter ! Mets une flèche dedans, et touche le nombre pour choisir combien de fois.',
    'robot.intro.free': 'C’est toi qui décides ! Glisse la station, des rochers et des étoiles sur la grille, puis appuie sur la flèche verte.',
    'robot.freeProgram': 'À toi de programmer le robot !',
    'robot.freeSuccess': 'Bravo ! Tu peux changer le décor avec le marteau.',
    'robot.fullRepeat': 'La bande est pleine ! Essaie la carte Répéter.',
    'robot.bonus': 'Le chemin le plus court ! Une étoile en plus !',
    'robot.shorter': 'Bravo ! Et avec moins de cartes, tu y arriverais ?',
    'robot.card.repeat': 'Répéter',
    'robot.times': '{n} fois',
    'robot.back': 'Effacer la dernière carte',
    'robot.edit': 'Changer le décor',
    'robot.toProgram': 'Programmer le robot',
    'robot.clearGrid': 'Vider la grille',
    'robot.thing.robot': 'Le robot', 'robot.thing.station': 'La station', 'robot.thing.rock': 'Un rocher', 'robot.thing.star': 'Une étoile',
  },
  es: {
    'robot.chooseLevel': '¡Elige un nivel!',
    'robot.ask.1': '¡Ayuda al robot a volver a su estación!',
    'robot.ask.2': '¡El robot necesita cargar sus pilas! Muéstrale el camino.',
    'robot.ask.3': '¡Bip bip! ¿Dónde está mi estación? ¡Prográmame!',
    'robot.howTo': '¡Arrastra las flechas a la tira y luego aprieta el botón verde!',
    'robot.run': 'Ejecutar el programa',
    'robot.step': 'Un paso',
    'robot.clear': 'Borrar todo',
    'robot.card.up': 'Arriba', 'robot.card.down': 'Abajo', 'robot.card.left': 'Izquierda', 'robot.card.right': 'Derecha',
    'robot.bumpRock.1': '¡Bong! ¡Una roca! Un pequeño error para arreglar: mira la carta naranja.',
    'robot.bumpRock.2': '¡Ay, mi nariz de robot! Hay un error en la carta naranja.',
    'robot.bumpEdge.1': '¡Uy, el borde del mundo! Mira la carta naranja.',
    'robot.bumpEdge.2': '¡Alto! No puedo salir de la cuadrícula. ¡Arregla la carta naranja!',
    'robot.short': '¡Faltan flechas para llegar a la estación! Agrega cartas.',
    'robot.stars': '¡Te olvidaste una estrella! Búscala antes de la estación.',
    'robot.empty': '¡Primero pon flechas en la tira!',
    'robot.full': '¡La tira está llena!',
    'robot.hintNext': '¡Mira la casilla que brilla: ahí hay que ir!',
    'robot.hintPath': '¡Sigue los pasitos hasta la estación!',
    'robot.success.1': 'Bzzz… ¡Cargado! ¡Gracias!',
    'robot.success.2': '¡Bip bip! ¡Llegué! ¡Súper programa!',
    'robot.success.3': '¡Bravo, programadora! ¡Mis pilas están llenas!',
    'robot.levelDone': '¡Bravo! ¡Terminaste el nivel!',
    'robot.continue': 'Continuar',
    'robot.level': 'Nivel {n}',
    'robot.intro.stars': '¡Junta la estrella en el camino y luego ve a la estación!',
    'robot.intro.repeat': '¡Carta nueva: Repetir! Pon una flecha adentro y toca el número para elegir cuántas veces.',
    'robot.intro.free': '¡Tú decides! Arrastra la estación, rocas y estrellas a la cuadrícula, y luego aprieta la flecha verde.',
    'robot.freeProgram': '¡Ahora programa al robot!',
    'robot.freeSuccess': '¡Bravo! Puedes cambiar el decorado con el martillo.',
    'robot.fullRepeat': '¡La tira está llena! Prueba la carta Repetir.',
    'robot.bonus': '¡El camino más corto! ¡Una estrella extra!',
    'robot.shorter': '¡Bravo! ¿Y con menos cartas, podrías?',
    'robot.card.repeat': 'Repetir',
    'robot.times': '{n} veces',
    'robot.back': 'Borrar la última carta',
    'robot.edit': 'Cambiar el decorado',
    'robot.toProgram': 'Programar el robot',
    'robot.clearGrid': 'Vaciar la cuadrícula',
    'robot.thing.robot': 'El robot', 'robot.thing.station': 'La estación', 'robot.thing.rock': 'Una roca', 'robot.thing.star': 'Una estrella',
  },
  en: {
    'robot.chooseLevel': 'Pick a level!',
    'robot.ask.1': 'Help the robot get back to its charging station!',
    'robot.ask.2': 'The robot needs to recharge! Show it the way.',
    'robot.ask.3': 'Beep beep! Where is my station? Program me!',
    'robot.howTo': 'Drag the arrows into the strip, then press the green button!',
    'robot.run': 'Run the program',
    'robot.step': 'One step',
    'robot.clear': 'Clear everything',
    'robot.card.up': 'Up', 'robot.card.down': 'Down', 'robot.card.left': 'Left', 'robot.card.right': 'Right',
    'robot.bumpRock.1': 'Bonk! A rock! A little bug to fix: look at the orange card.',
    'robot.bumpRock.2': 'Ouch, my robot nose! There is a bug on the orange card.',
    'robot.bumpEdge.1': 'Whoa, the edge of the world! Look at the orange card.',
    'robot.bumpEdge.2': 'Stop! I can’t leave the grid. Fix the orange card!',
    'robot.short': 'Not enough arrows to reach the station! Add some cards.',
    'robot.stars': 'You forgot a star! Get it before the station.',
    'robot.empty': 'Put some arrows in the strip first!',
    'robot.full': 'The strip is full!',
    'robot.hintNext': 'Look at the shining square: that’s where to go!',
    'robot.hintPath': 'Follow the little footsteps to the station!',
    'robot.success.1': 'Bzzz… Recharged! Thank you!',
    'robot.success.2': 'Beep beep! I made it! Super program!',
    'robot.success.3': 'Well done, programmer! My batteries are full!',
    'robot.levelDone': 'Well done! You finished the level!',
    'robot.continue': 'Continue',
    'robot.level': 'Level {n}',
    'robot.intro.stars': 'Pick up the star on the way, then go to the station!',
    'robot.intro.repeat': 'New card: Repeat! Put an arrow inside, and tap the number to choose how many times.',
    'robot.intro.free': 'You decide! Drag the station, rocks and stars onto the grid, then press the green arrow.',
    'robot.freeProgram': 'Now program the robot!',
    'robot.freeSuccess': 'Well done! You can change the scenery with the hammer.',
    'robot.fullRepeat': 'The strip is full! Try the Repeat card.',
    'robot.bonus': 'The shortest way! One more star!',
    'robot.shorter': 'Well done! Could you do it with fewer cards?',
    'robot.card.repeat': 'Repeat',
    'robot.times': '{n} times',
    'robot.back': 'Remove the last card',
    'robot.edit': 'Change the scenery',
    'robot.toProgram': 'Program the robot',
    'robot.clearGrid': 'Empty the grid',
    'robot.thing.robot': 'The robot', 'robot.thing.station': 'The station', 'robot.thing.rock': 'A rock', 'robot.thing.star': 'A star',
  },
};
