// Everything "Qui mange qui ?" says, in fr / es / en.
// (The title is in meta.js: the hub needs it before the game loads.)
// food.name.<id>    = every plant and animal in levels.js (with its article, said aloud)
// food.habitat.<id> = every scene in levels.js HABITATS
export default {
  fr: {
    'food.chooseLevel': 'Choisis un niveau !',
    'food.level': 'Niveau {n}',
    'food.levelDone': 'Bravo ! Tu connais bien les animaux !',
    'food.continue': 'Continuer',
    'food.tray': 'La nourriture',
    'food.ask.feed': 'Qu’est-ce que {a} mange ? Donne-lui à manger !',
    'food.yum': 'Miam ! {A} mange {b} !',
    'food.yuck.1': 'Beurk ! Pas ça !',
    'food.yuck.2': 'Oh non, beurk !',
    'food.yuck.3': 'Beurk, beurk !',
    'food.clue.plant': '{A} mange des plantes.',
    'food.clue.animal': '{A} mange des petits animaux.',
    'food.hint.look': 'Regarde bien les trois.',
    'food.hint.glow': 'Regarde celui qui brille !',
    'food.hint.dance': 'Essaie celui qui danse !',
    'food.again.1': 'Essaie encore !',
    'food.again.2': 'Presque ! Encore une fois !',
    'food.again.3': 'Tu vas trouver !',
    'food.intro.home': 'Chaque animal a sa maison. Emmène-les chez eux !',
    'food.intro.feedHard': 'Attention, c’est plus difficile ! Regarde bien ce que chaque animal mange.',
    'food.intro.chain': 'Qui mange qui ? Range-les dans l’ordre : chacun est mangé par le suivant !',
    'food.intro.decoy': 'Attention, un animal s’est glissé ici par erreur. Il ne va pas dans la chaîne !',
    'food.intro.long': 'Maintenant, une chaîne encore plus longue !',
    'food.habitat.forest': 'la forêt', 'food.habitat.mountain': 'la montagne',
    'food.habitat.savanna': 'la savane', 'food.habitat.ice': 'la banquise', 'food.habitat.sea': 'la mer',
    'food.name.grass': 'l’herbe', 'food.name.leaves': 'les feuilles', 'food.name.carrot': 'la carotte',
    'food.name.nut': 'la noisette', 'food.name.seeds': 'les graines', 'food.name.berries': 'les baies',
    'food.name.flower': 'la fleur', 'food.name.algae': 'les algues',
    'food.name.rabbit': 'le lapin', 'food.name.squirrel': 'l’écureuil', 'food.name.hedgehog': 'le hérisson',
    'food.name.mouse': 'la souris', 'food.name.owl': 'la chouette', 'food.name.frog': 'la grenouille',
    'food.name.fox': 'le renard', 'food.name.bear': 'l’ours', 'food.name.worm': 'le ver de terre',
    'food.name.fly': 'la mouche', 'food.name.grasshopper': 'la sauterelle', 'food.name.marmot': 'la marmotte',
    'food.name.ibex': 'le bouquetin', 'food.name.eagle': 'l’aigle', 'food.name.lion': 'le lion',
    'food.name.zebra': 'le zèbre', 'food.name.giraffe': 'la girafe', 'food.name.elephant': 'l’éléphant',
    'food.name.penguin': 'le manchot', 'food.name.seal': 'le phoque', 'food.name.orca': 'l’orque',
    'food.name.krill': 'le krill', 'food.name.fish': 'le poisson', 'food.name.turtle': 'la tortue de mer',
    'food.name.crab': 'le crabe',
  },
  es: {
    'food.chooseLevel': '¡Elige un nivel!',
    'food.level': 'Nivel {n}',
    'food.levelDone': '¡Bravo! ¡Conoces muy bien a los animales!',
    'food.continue': 'Continuar',
    'food.tray': 'La comida',
    'food.ask.feed': '¿Qué come {a}? ¡Dale de comer!',
    'food.yum': '¡Ñam! {A} come {b}.',
    'food.yuck.1': '¡Puaj! ¡Eso no!',
    'food.yuck.2': '¡Oh no, puaj!',
    'food.yuck.3': '¡Puaj, puaj!',
    'food.clue.plant': '{A} come plantas.',
    'food.clue.animal': '{A} come animalitos.',
    'food.hint.look': 'Mira bien los tres.',
    'food.hint.glow': '¡Mira el que brilla!',
    'food.hint.dance': '¡Prueba el que baila!',
    'food.again.1': '¡Prueba otra vez!',
    'food.again.2': '¡Casi! ¡Otra vez!',
    'food.again.3': '¡Lo vas a encontrar!',
    'food.intro.home': 'Cada animal tiene su casa. ¡Llévalos a casa!',
    'food.intro.feedHard': '¡Atención, ahora es más difícil! Mira bien lo que come cada animal.',
    'food.intro.chain': '¿Quién se come a quién? Ponlos en orden: ¡a cada uno se lo come el siguiente!',
    'food.intro.decoy': 'Atención, un animal se ha colado aquí por error. ¡No va en la cadena!',
    'food.intro.long': '¡Ahora, una cadena todavía más larga!',
    'food.habitat.forest': 'el bosque', 'food.habitat.mountain': 'la montaña',
    'food.habitat.savanna': 'la sabana', 'food.habitat.ice': 'el hielo', 'food.habitat.sea': 'el mar',
    'food.name.grass': 'la hierba', 'food.name.leaves': 'las hojas', 'food.name.carrot': 'la zanahoria',
    'food.name.nut': 'la avellana', 'food.name.seeds': 'las semillas', 'food.name.berries': 'las bayas',
    'food.name.flower': 'la flor', 'food.name.algae': 'las algas',
    'food.name.rabbit': 'el conejo', 'food.name.squirrel': 'la ardilla', 'food.name.hedgehog': 'el erizo',
    'food.name.mouse': 'el ratón', 'food.name.owl': 'el búho', 'food.name.frog': 'la rana',
    'food.name.fox': 'el zorro', 'food.name.bear': 'el oso', 'food.name.worm': 'la lombriz',
    'food.name.fly': 'la mosca', 'food.name.grasshopper': 'el saltamontes', 'food.name.marmot': 'la marmota',
    'food.name.ibex': 'la cabra montés', 'food.name.eagle': 'el águila', 'food.name.lion': 'el león',
    'food.name.zebra': 'la cebra', 'food.name.giraffe': 'la jirafa', 'food.name.elephant': 'el elefante',
    'food.name.penguin': 'el pingüino', 'food.name.seal': 'la foca', 'food.name.orca': 'la orca',
    'food.name.krill': 'el kril', 'food.name.fish': 'el pez', 'food.name.turtle': 'la tortuga marina',
    'food.name.crab': 'el cangrejo',
  },
  en: {
    'food.chooseLevel': 'Choose a level!',
    'food.level': 'Level {n}',
    'food.levelDone': 'Well done! You know the animals well!',
    'food.continue': 'Continue',
    'food.tray': 'The food',
    'food.ask.feed': 'What does {a} eat? Feed it!',
    'food.yum': 'Yum! {A} eats {b}!',
    'food.yuck.1': 'Yuck! Not that!',
    'food.yuck.2': 'Oh no, yuck!',
    'food.yuck.3': 'Yuck, yuck!',
    'food.clue.plant': '{A} eats plants.',
    'food.clue.animal': '{A} eats little animals.',
    'food.hint.look': 'Look carefully at all three.',
    'food.hint.glow': 'Look at the shiny one!',
    'food.hint.dance': 'Try the one that is dancing!',
    'food.again.1': 'Try again!',
    'food.again.2': 'Almost! One more time!',
    'food.again.3': 'You can find it!',
    'food.intro.home': 'Every animal has a home. Take them home!',
    'food.intro.feedHard': 'Careful, this is harder! Look closely at what each animal eats.',
    'food.intro.chain': 'Who eats whom? Put them in order: each one is eaten by the next one!',
    'food.intro.decoy': 'Careful, one animal got in here by mistake. It doesn’t go in the chain!',
    'food.intro.long': 'Now, an even longer chain!',
    'food.habitat.forest': 'the forest', 'food.habitat.mountain': 'the mountain',
    'food.habitat.savanna': 'the savanna', 'food.habitat.ice': 'the ice', 'food.habitat.sea': 'the sea',
    'food.name.grass': 'the grass', 'food.name.leaves': 'the leaves', 'food.name.carrot': 'the carrot',
    'food.name.nut': 'the hazelnut', 'food.name.seeds': 'the seeds', 'food.name.berries': 'the berries',
    'food.name.flower': 'the flower', 'food.name.algae': 'the algae',
    'food.name.rabbit': 'the rabbit', 'food.name.squirrel': 'the squirrel', 'food.name.hedgehog': 'the hedgehog',
    'food.name.mouse': 'the mouse', 'food.name.owl': 'the owl', 'food.name.frog': 'the frog',
    'food.name.fox': 'the fox', 'food.name.bear': 'the bear', 'food.name.worm': 'the earthworm',
    'food.name.fly': 'the fly', 'food.name.grasshopper': 'the grasshopper', 'food.name.marmot': 'the marmot',
    'food.name.ibex': 'the ibex', 'food.name.eagle': 'the eagle', 'food.name.lion': 'the lion',
    'food.name.zebra': 'the zebra', 'food.name.giraffe': 'the giraffe', 'food.name.elephant': 'the elephant',
    'food.name.penguin': 'the penguin', 'food.name.seal': 'the seal', 'food.name.orca': 'the orca',
    'food.name.krill': 'the krill', 'food.name.fish': 'the fish', 'food.name.turtle': 'the sea turtle',
    'food.name.crab': 'the crab',
  },
};
