// Everything "La Balance" says, in fr / es / en.
// (The title is in meta.js: the hub needs it before the game loads.)
// balance.obj.* = object names (one per object in levels.js OBJECTS).
export default {
  fr: {
    'balance.chooseLevel': 'Choisis un niveau !',
    'balance.level': 'Niveau {n}',
    'balance.place': 'Pose les deux objets sur la balance !',
    'balance.howTo': 'Le côté qui descend, c’est le plus lourd.',
    'balance.intro.surprise': 'Attention, les gros objets ne sont pas toujours les plus lourds !',
    'balance.intro.light': 'Écoute bien : parfois je demande le plus lourd, parfois le plus léger !',
    'balance.tray': 'Les objets à peser',
    'balance.pan.left': 'Plateau de gauche',
    'balance.pan.right': 'Plateau de droite',
    'balance.ask.heavy': 'Lequel est le plus lourd ? Pose-le sur le podium !',
    'balance.ask.light': 'Lequel est le plus léger ? Pose-le sur le podium !',
    'balance.podium': 'Le podium',
    'balance.weighFirst': 'Pèse-les d’abord sur la balance !',
    'balance.hint.heavy': 'Regarde la balance : le côté qui descend, c’est le plus lourd.',
    'balance.hint.light': 'Regarde la balance : le côté qui monte, c’est le plus léger.',
    'balance.hint.arrow': 'Regarde la flèche !',
    'balance.hint.wiggle': 'Essaie celui qui danse !',
    'balance.wrong.1': 'Hmm, pas celui-là ! Regarde bien la balance.',
    'balance.wrong.2': 'Oups ! Essaie encore !',
    'balance.wrong.3': 'Presque ! Regarde de quel côté ça penche.',
    'balance.right.1': 'Bravo ! Tu as trouvé !',
    'balance.right.2': 'Super ! C’est ça !',
    'balance.right.3': 'Oui ! Bien pesé !',
    'balance.levelDone': 'Bravo ! Tu as tout pesé !',
    'balance.continue': 'Continuer',
    'balance.obj.balloon': 'le ballon', 'balance.obj.apple': 'la pomme', 'balance.obj.teddy': 'le nounours',
    'balance.obj.pillow': 'le coussin', 'balance.obj.ball': 'la boule', 'balance.obj.pineapple': 'l’ananas',
    'balance.obj.stone': 'la pierre', 'balance.obj.watermelon': 'la pastèque', 'balance.obj.pumpkin': 'la citrouille',
  },
  es: {
    'balance.chooseLevel': '¡Elige un nivel!',
    'balance.level': 'Nivel {n}',
    'balance.place': '¡Pon los dos objetos en la balanza!',
    'balance.howTo': 'El lado que baja es el más pesado.',
    'balance.intro.surprise': '¡Atención, los objetos grandes no siempre son los más pesados!',
    'balance.intro.light': '¡Escucha bien: a veces pido el más pesado y a veces el más ligero!',
    'balance.tray': 'Los objetos para pesar',
    'balance.pan.left': 'Platillo de la izquierda',
    'balance.pan.right': 'Platillo de la derecha',
    'balance.ask.heavy': '¿Cuál es el más pesado? ¡Ponlo en el podio!',
    'balance.ask.light': '¿Cuál es el más ligero? ¡Ponlo en el podio!',
    'balance.podium': 'El podio',
    'balance.weighFirst': '¡Primero pésalos en la balanza!',
    'balance.hint.heavy': 'Mira la balanza: el lado que baja es el más pesado.',
    'balance.hint.light': 'Mira la balanza: el lado que sube es el más ligero.',
    'balance.hint.arrow': '¡Mira la flecha!',
    'balance.hint.wiggle': '¡Prueba el que baila!',
    'balance.wrong.1': 'Mmm, ¡ese no! Mira bien la balanza.',
    'balance.wrong.2': '¡Uy! ¡Prueba otra vez!',
    'balance.wrong.3': '¡Casi! Mira hacia qué lado se inclina.',
    'balance.right.1': '¡Bravo! ¡Lo encontraste!',
    'balance.right.2': '¡Genial! ¡Es ese!',
    'balance.right.3': '¡Sí! ¡Bien pesado!',
    'balance.levelDone': '¡Bravo! ¡Lo pesaste todo!',
    'balance.continue': 'Continuar',
    'balance.obj.balloon': 'el globo', 'balance.obj.apple': 'la manzana', 'balance.obj.teddy': 'el osito',
    'balance.obj.pillow': 'el cojín', 'balance.obj.ball': 'la bola', 'balance.obj.pineapple': 'la piña',
    'balance.obj.stone': 'la piedra', 'balance.obj.watermelon': 'la sandía', 'balance.obj.pumpkin': 'la calabaza',
  },
  en: {
    'balance.chooseLevel': 'Choose a level!',
    'balance.level': 'Level {n}',
    'balance.place': 'Put both things on the scales!',
    'balance.howTo': 'The side that goes down is the heavier one.',
    'balance.intro.surprise': 'Careful, big things are not always the heaviest!',
    'balance.intro.light': 'Listen carefully: sometimes I ask for the heavier one, sometimes the lighter one!',
    'balance.tray': 'Things to weigh',
    'balance.pan.left': 'Left pan',
    'balance.pan.right': 'Right pan',
    'balance.ask.heavy': 'Which one is heavier? Put it on the podium!',
    'balance.ask.light': 'Which one is lighter? Put it on the podium!',
    'balance.podium': 'The podium',
    'balance.weighFirst': 'Weigh them on the scales first!',
    'balance.hint.heavy': 'Look at the scales: the side that goes down is the heavier one.',
    'balance.hint.light': 'Look at the scales: the side that goes up is the lighter one.',
    'balance.hint.arrow': 'Look at the arrow!',
    'balance.hint.wiggle': 'Try the one that is dancing!',
    'balance.wrong.1': 'Hmm, not that one! Look at the scales.',
    'balance.wrong.2': 'Oops! Try again!',
    'balance.wrong.3': 'Almost! Look at which way it leans.',
    'balance.right.1': 'Well done! You found it!',
    'balance.right.2': 'Great! That’s the one!',
    'balance.right.3': 'Yes! Well weighed!',
    'balance.levelDone': 'Well done! You weighed everything!',
    'balance.continue': 'Continue',
    'balance.obj.balloon': 'the balloon', 'balance.obj.apple': 'the apple', 'balance.obj.teddy': 'the teddy bear',
    'balance.obj.pillow': 'the pillow', 'balance.obj.ball': 'the metal ball', 'balance.obj.pineapple': 'the pineapple',
    'balance.obj.stone': 'the stone', 'balance.obj.watermelon': 'the watermelon', 'balance.obj.pumpkin': 'the pumpkin',
  },
};
