// Everything "La Balance" says, in fr / es / en.
// (The title is in meta.js: the hub needs it before the game loads.)
// balance.obj.* = object names (one per object in levels.js OBJECTS).
export default {
  fr: {
    'balance.chooseLevel': 'Choisis un niveau !',
    'balance.level': 'Niveau {n}',
    'balance.place': 'Pose les deux objets sur la balance !',
    'balance.howTo': 'Le côté qui descend, c’est le plus lourd.',
    'balance.intro.surprise': 'Attention, les gros objets ne sont pas toujours les plus lourds !',
    'balance.intro.light': 'Écoute bien : parfois je demande le plus lourd, parfois le plus léger !',
    'balance.tray': 'Les objets à peser',
    'balance.pan.left': 'Plateau de gauche',
    'balance.pan.right': 'Plateau de droite',
    'balance.ask.heavy': 'Lequel est le plus lourd ? Pose-le sur le podium !',
    'balance.ask.light': 'Lequel est le plus léger ? Pose-le sur le podium !',
    'balance.podium': 'Le podium',
    'balance.weighFirst': 'Pèse-les d’abord sur la balance !',
    'balance.hint.heavy': 'Regarde la balance : le côté qui descend, c’est le plus lourd.',
    'balance.hint.light': 'Regarde la balance : le côté qui monte, c’est le plus léger.',
    'balance.hint.arrow': 'Regarde la flèche !',
    'balance.hint.wiggle': 'Essaie celui qui danse !',
    'balance.wrong.1': 'Hmm, pas celui-là ! Regarde bien la balance.',
    'balance.wrong.2': 'Oups ! Essaie encore !',
    'balance.wrong.3': 'Presque ! Regarde de quel côté ça penche.',
    'balance.right.1': 'Bravo ! Tu as trouvé !',
    'balance.right.2': 'Super ! C’est ça !',
    'balance.right.3': 'Oui ! Bien pesé !',
    'balance.levelDone': 'Bravo ! Tu as tout pesé !',
    'balance.continue': 'Continuer',
    'balance.intro.cubes': 'Combien de cubes pèse-t-il ? Mets des cubes de l’autre côté jusqu’à ce que la balance soit bien droite !',
    'balance.intro.two': 'Maintenant, il y a deux objets ! Combien de cubes pour les deux ensemble ? Mets des cubes jusqu’à ce que la balance soit bien droite !',
    'balance.cubes.ask': 'Mets des cubes jusqu’à ce que la balance soit bien droite !',
    'balance.cubes.source': 'Un cube',
    'balance.cubes.frame': 'Les cubes : touche pour en enlever un',
    'balance.weighs.one': '{a} pèse {n} cube !',
    'balance.weighs.other': '{a} pèse {n} cubes !',
    'balance.weighsTwo.one': '{a} et {b} pèsent {n} cube !',
    'balance.weighsTwo.other': '{a} et {b} pèsent {n} cubes !',
    'balance.weighsThree.one': '{a}, {b} et {c} pèsent {n} cube !',
    'balance.weighsThree.other': '{a}, {b} et {c} pèsent {n} cubes !',
    'balance.placeThree': 'Pèse les objets deux par deux !',
    'balance.intro.three': 'Trois objets, mais seulement deux plateaux ! Pèse-les deux par deux pour trouver le plus lourd.',
    'balance.path': 'Appuie sur le bouton pour peser des objets !',
    'balance.intro.threeLight': 'Trois objets ! Pèse-les deux par deux. Écoute bien : parfois je cherche le plus lourd, parfois le plus léger !',
    'balance.intro.threeCubes': 'Trois objets ensemble ! Combien de cubes pour les trois ? Mets des cubes jusqu’à ce que la balance soit bien droite !',
    'balance.hint.pairs': 'Pèse-les deux par deux : garde le plus lourd sur la balance et essaie-le avec le dernier !',
    'balance.panFull': 'La balance est pleine ! Touche un objet sur la balance pour l’enlever.',
    'balance.free.intro': 'Joue comme tu veux ! Pose ce que tu veux sur la balance, et des cubes aussi. Tu peux trouver deux choses qui pèsent pareil ?',
    'balance.free.level': 'Équilibré ! Les deux côtés pèsent pareil !',
    'balance.cubes.full': 'Il n’y a plus de place pour les cubes de ce côté !',
    'balance.obj.balloon': 'le ballon', 'balance.obj.apple': 'la pomme', 'balance.obj.teddy': 'le nounours',
    'balance.obj.pillow': 'le coussin', 'balance.obj.ball': 'la boule', 'balance.obj.pineapple': 'l’ananas',
    'balance.obj.stone': 'la pierre', 'balance.obj.watermelon': 'la pastèque', 'balance.obj.pumpkin': 'la citrouille',
  },
  es: {
    'balance.chooseLevel': '¡Elige un nivel!',
    'balance.level': 'Nivel {n}',
    'balance.place': '¡Pon los dos objetos en la balanza!',
    'balance.howTo': 'El lado que baja es el más pesado.',
    'balance.intro.surprise': '¡Atención, los objetos grandes no siempre son los más pesados!',
    'balance.intro.light': '¡Escucha bien: a veces pido el más pesado y a veces el más ligero!',
    'balance.tray': 'Los objetos para pesar',
    'balance.pan.left': 'Platillo de la izquierda',
    'balance.pan.right': 'Platillo de la derecha',
    'balance.ask.heavy': '¿Cuál es el más pesado? ¡Ponlo en el podio!',
    'balance.ask.light': '¿Cuál es el más ligero? ¡Ponlo en el podio!',
    'balance.podium': 'El podio',
    'balance.weighFirst': '¡Primero pésalos en la balanza!',
    'balance.hint.heavy': 'Mira la balanza: el lado que baja es el más pesado.',
    'balance.hint.light': 'Mira la balanza: el lado que sube es el más ligero.',
    'balance.hint.arrow': '¡Mira la flecha!',
    'balance.hint.wiggle': '¡Prueba el que baila!',
    'balance.wrong.1': 'Mmm, ¡ese no! Mira bien la balanza.',
    'balance.wrong.2': '¡Uy! ¡Prueba otra vez!',
    'balance.wrong.3': '¡Casi! Mira hacia qué lado se inclina.',
    'balance.right.1': '¡Bravo! ¡Lo encontraste!',
    'balance.right.2': '¡Genial! ¡Es ese!',
    'balance.right.3': '¡Sí! ¡Bien pesado!',
    'balance.levelDone': '¡Bravo! ¡Lo pesaste todo!',
    'balance.continue': 'Continuar',
    'balance.intro.cubes': '¿Cuántos cubos pesa? ¡Pon cubos del otro lado hasta que la balanza quede derecha!',
    'balance.intro.two': '¡Ahora hay dos objetos! ¿Cuántos cubos pesan los dos juntos? ¡Pon cubos hasta que la balanza quede derecha!',
    'balance.cubes.ask': '¡Pon cubos hasta que la balanza quede derecha!',
    'balance.cubes.source': 'Un cubo',
    'balance.cubes.frame': 'Los cubos: toca para quitar uno',
    'balance.weighs.one': '¡{a} pesa {n} cubo!',
    'balance.weighs.other': '¡{a} pesa {n} cubos!',
    'balance.weighsTwo.one': '¡{a} y {b} pesan {n} cubo!',
    'balance.weighsTwo.other': '¡{a} y {b} pesan {n} cubos!',
    'balance.weighsThree.one': '¡{a}, {b} y {c} pesan {n} cubo!',
    'balance.weighsThree.other': '¡{a}, {b} y {c} pesan {n} cubos!',
    'balance.placeThree': '¡Pesa los objetos de dos en dos!',
    'balance.intro.three': '¡Tres objetos, pero solo dos platillos! Pésalos de dos en dos para encontrar el más pesado.',
    'balance.path': '¡Pulsa el botón para pesar objetos!',
    'balance.intro.threeLight': '¡Tres objetos! Pésalos de dos en dos. Escucha bien: a veces busco el más pesado, a veces el más ligero.',
    'balance.intro.threeCubes': '¡Tres objetos juntos! ¿Cuántos cubos pesan los tres? ¡Pon cubos hasta que la balanza quede derecha!',
    'balance.hint.pairs': 'Pésalos de dos en dos: ¡deja el más pesado en la balanza y pruébalo con el último!',
    'balance.panFull': '¡La balanza está llena! Toca un objeto de la balanza para quitarlo.',
    'balance.free.intro': '¡Juega como quieras! Pon lo que quieras en la balanza, y cubos también. ¿Encuentras dos cosas que pesen lo mismo?',
    'balance.free.level': '¡Equilibrado! ¡Los dos lados pesan lo mismo!',
    'balance.cubes.full': '¡Ya no caben más cubos de este lado!',
    'balance.obj.balloon': 'el globo', 'balance.obj.apple': 'la manzana', 'balance.obj.teddy': 'el osito',
    'balance.obj.pillow': 'el cojín', 'balance.obj.ball': 'la bola', 'balance.obj.pineapple': 'la piña',
    'balance.obj.stone': 'la piedra', 'balance.obj.watermelon': 'la sandía', 'balance.obj.pumpkin': 'la calabaza',
  },
  en: {
    'balance.chooseLevel': 'Choose a level!',
    'balance.level': 'Level {n}',
    'balance.place': 'Put both things on the scales!',
    'balance.howTo': 'The side that goes down is the heavier one.',
    'balance.intro.surprise': 'Careful, big things are not always the heaviest!',
    'balance.intro.light': 'Listen carefully: sometimes I ask for the heavier one, sometimes the lighter one!',
    'balance.tray': 'Things to weigh',
    'balance.pan.left': 'Left pan',
    'balance.pan.right': 'Right pan',
    'balance.ask.heavy': 'Which one is heavier? Put it on the podium!',
    'balance.ask.light': 'Which one is lighter? Put it on the podium!',
    'balance.podium': 'The podium',
    'balance.weighFirst': 'Weigh them on the scales first!',
    'balance.hint.heavy': 'Look at the scales: the side that goes down is the heavier one.',
    'balance.hint.light': 'Look at the scales: the side that goes up is the lighter one.',
    'balance.hint.arrow': 'Look at the arrow!',
    'balance.hint.wiggle': 'Try the one that is dancing!',
    'balance.wrong.1': 'Hmm, not that one! Look at the scales.',
    'balance.wrong.2': 'Oops! Try again!',
    'balance.wrong.3': 'Almost! Look at which way it leans.',
    'balance.right.1': 'Well done! You found it!',
    'balance.right.2': 'Great! That’s the one!',
    'balance.right.3': 'Yes! Well weighed!',
    'balance.levelDone': 'Well done! You weighed everything!',
    'balance.continue': 'Continue',
    'balance.intro.cubes': 'How many cubes does it weigh? Put cubes on the other side until the scales are straight!',
    'balance.intro.two': 'Now there are two things! How many cubes for both together? Put cubes on until the scales are straight!',
    'balance.cubes.ask': 'Put cubes on until the scales are straight!',
    'balance.cubes.source': 'A cube',
    'balance.cubes.frame': 'The cubes: touch to take one off',
    'balance.weighs.one': '{a} weighs {n} cube!',
    'balance.weighs.other': '{a} weighs {n} cubes!',
    'balance.weighsTwo.one': '{a} and {b} weigh {n} cube!',
    'balance.weighsTwo.other': '{a} and {b} weigh {n} cubes!',
    'balance.weighsThree.one': '{a}, {b} and {c} weigh {n} cube!',
    'balance.weighsThree.other': '{a}, {b} and {c} weigh {n} cubes!',
    'balance.placeThree': 'Weigh the things two at a time!',
    'balance.intro.three': 'Three things, but only two pans! Weigh them two at a time to find the heaviest.',
    'balance.path': 'Press the button to weigh things!',
    'balance.intro.threeLight': 'Three things! Weigh them two at a time. Listen well: sometimes I want the heaviest, sometimes the lightest!',
    'balance.intro.threeCubes': 'Three things together! How many cubes for all three? Put cubes on until the scales are straight!',
    'balance.hint.pairs': 'Weigh them two at a time: keep the heavier one on the scales and try it with the last one!',
    'balance.panFull': 'The scales are full! Touch a thing on the scales to take it off.',
    'balance.free.intro': 'Play however you like! Put anything on the scales, and cubes too. Can you find two things that weigh the same?',
    'balance.free.level': 'Balanced! Both sides weigh the same!',
    'balance.cubes.full': 'There is no more room for cubes on this side!',
    'balance.obj.balloon': 'the balloon', 'balance.obj.apple': 'the apple', 'balance.obj.teddy': 'the teddy bear',
    'balance.obj.pillow': 'the pillow', 'balance.obj.ball': 'the metal ball', 'balance.obj.pineapple': 'the pineapple',
    'balance.obj.stone': 'the stone', 'balance.obj.watermelon': 'the watermelon', 'balance.obj.pumpkin': 'the pumpkin',
  },
};
