// Everything "Le Train des Suites" says, in fr / es / en.
// (The title is in meta.js: the hub needs it before the game loads.)
export default {
  fr: {
    'train.chooseLevel': 'Choisis un niveau !',
    'train.level': 'Niveau {n}',
    'train.howTo': 'Regarde bien le train : les wagons se suivent toujours pareil. Glisse le bon wagon dans le trou !',
    'train.ask': 'Il manque un wagon ! Lequel va dans le trou ?',
    'train.tray': 'Les wagons à placer',
    'train.empty': 'Wagon vide',
    'train.wrong.1': 'Hmm, pas celui-là ! Regarde bien le train.',
    'train.wrong.2': 'Oups ! Le train n’en veut pas. Essaie un autre !',
    'train.wrong.3': 'Presque ! Regarde les wagons et essaie encore.',
    'train.right.1': 'Bravo ! Tchou tchou !',
    'train.right.2': 'Super ! Le train peut partir !',
    'train.right.3': 'Oui ! C’est le bon wagon !',
    'train.levelDone': 'Bravo ! Tous les trains sont partis !',
    'train.continue': 'Continuer',
  },
  es: {
    'train.chooseLevel': '¡Elige un nivel!',
    'train.level': 'Nivel {n}',
    'train.howTo': 'Mira bien el tren: los vagones siempre se siguen igual. ¡Arrastra el vagón correcto al hueco!',
    'train.ask': '¡Falta un vagón! ¿Cuál va en el hueco?',
    'train.tray': 'Los vagones para colocar',
    'train.empty': 'Vagón vacío',
    'train.wrong.1': 'Mmm, ¡ese no! Mira bien el tren.',
    'train.wrong.2': '¡Uy! El tren no lo quiere. ¡Prueba otro!',
    'train.wrong.3': '¡Casi! Mira los vagones y prueba otra vez.',
    'train.right.1': '¡Bravo! ¡Chu chu!',
    'train.right.2': '¡Genial! ¡El tren puede salir!',
    'train.right.3': '¡Sí! ¡Es el vagón correcto!',
    'train.levelDone': '¡Bravo! ¡Todos los trenes han salido!',
    'train.continue': 'Continuar',
  },
  en: {
    'train.chooseLevel': 'Choose a level!',
    'train.level': 'Level {n}',
    'train.howTo': 'Look at the train: the wagons always follow the same way. Drag the right wagon into the gap!',
    'train.ask': 'A wagon is missing! Which one goes in the gap?',
    'train.tray': 'Wagons to place',
    'train.empty': 'Empty wagon',
    'train.wrong.1': 'Hmm, not that one! Look at the train.',
    'train.wrong.2': 'Oops! The train doesn’t want it. Try another one!',
    'train.wrong.3': 'Almost! Look at the wagons and try again.',
    'train.right.1': 'Well done! Choo choo!',
    'train.right.2': 'Great! The train can leave!',
    'train.right.3': 'Yes! That’s the right wagon!',
    'train.levelDone': 'Well done! All the trains have left!',
    'train.continue': 'Continue',
  },
};
