// Everything "Le Train des Suites" says, in fr / es / en.
// (The title is in meta.js: the hub needs it before the game loads.)
// train.token.* = the names the "singing train" hint says (one per token in art.js).
export default {
  fr: {
    'train.chooseLevel': 'Choisis un niveau !',
    'train.level': 'Niveau {n}',
    'train.howTo': 'Regarde bien le train : les wagons se suivent toujours pareil. Glisse le bon wagon dans le trou !',
    'train.ask': 'Il manque un wagon ! Lequel va dans le trou ?',
    'train.askMany': 'Il manque des wagons ! Remplis tous les trous.',
    'train.free.intro': 'Invente le début de ton train ! Mets deux, trois ou quatre wagons, puis appuie sur le bouton vert.',
    'train.free.go': 'Faire partir le train',
    'train.free.full': 'Ton début est complet ! Touche un wagon pour l’enlever, ou appuie sur le bouton vert.',
    'train.free.needMore': 'Mets au moins deux wagons !',
    'train.free.again': 'Encore ! Pour changer un wagon, touche-le pour l’enlever.',
    'train.tray': 'Les wagons à placer',
    'train.empty': 'Wagon vide',
    'train.wrong.1': 'Hmm, pas celui-là ! Regarde bien le train.',
    'train.wrong.2': 'Oups ! Le train n’en veut pas. Essaie un autre !',
    'train.wrong.3': 'Presque ! Regarde les wagons et essaie encore.',
    'train.right.1': 'Bravo ! Tchou tchou !',
    'train.right.2': 'Super ! Le train peut partir !',
    'train.right.3': 'Oui ! C’est le bon wagon !',
    'train.levelDone': 'Bravo ! Tous les trains sont partis !',
    'train.continue': 'Continuer',
    'train.hintSing': 'Écoute le train : {list}… et après ?',
    'train.hintPeriod': 'Regarde les wagons entourés : c’est ça qui se répète !',
    'train.hintToken': 'Essaie le wagon qui danse !',
    // Token names (a colour; each colour also has its own shape).
    'train.token.red': 'rouge', 'train.token.blue': 'bleu', 'train.token.yellow': 'jaune',
    'train.token.green': 'vert', 'train.token.purple': 'violet',
    'train.token.apple': 'pomme', 'train.token.banana': 'banane', 'train.token.grapes': 'raisin',
    'train.token.pear': 'poire', 'train.token.watermelon': 'pastèque',
    'train.intro.fruits': 'Maintenant, le train transporte des fruits !',
    'train.intro.double': 'Regarde bien : parfois, le même wagon vient deux fois de suite !',
    'train.intro.middle': 'Attention : cette fois, le trou peut être au milieu du train !',
    'train.intro.period': 'Tu peux les remplir dans l’ordre que tu veux.',
    'train.intro.grow': 'Regarde bien les points dans les wagons : combien y en a-t-il ?',
    'train.hintGrow': 'Regarde le point orange : à chaque wagon, il y a un point de plus !',
    'train.hintShrink': 'Regarde le rond orange : à chaque wagon, il y a un point de moins !',
    'train.token.dots1': 'un', 'train.token.dots2': 'deux', 'train.token.dots3': 'trois',
    'train.token.dots4': 'quatre', 'train.token.dots5': 'cinq',
  },
  es: {
    'train.chooseLevel': '¡Elige un nivel!',
    'train.level': 'Nivel {n}',
    'train.howTo': 'Mira bien el tren: los vagones siempre se siguen igual. ¡Arrastra el vagón correcto al hueco!',
    'train.ask': '¡Falta un vagón! ¿Cuál va en el hueco?',
    'train.askMany': '¡Faltan vagones! Llena todos los huecos.',
    'train.free.intro': '¡Inventa el comienzo de tu tren! Pon dos, tres o cuatro vagones y luego pulsa el botón verde.',
    'train.free.go': 'Hacer salir el tren',
    'train.free.full': '¡Tu comienzo está completo! Toca un vagón para quitarlo, o pulsa el botón verde.',
    'train.free.needMore': '¡Pon al menos dos vagones!',
    'train.free.again': '¡Otra vez! Para cambiar un vagón, tócalo para quitarlo.',
    'train.tray': 'Los vagones para colocar',
    'train.empty': 'Vagón vacío',
    'train.wrong.1': 'Mmm, ¡ese no! Mira bien el tren.',
    'train.wrong.2': '¡Uy! El tren no lo quiere. ¡Prueba otro!',
    'train.wrong.3': '¡Casi! Mira los vagones y prueba otra vez.',
    'train.right.1': '¡Bravo! ¡Chu chu!',
    'train.right.2': '¡Genial! ¡El tren puede salir!',
    'train.right.3': '¡Sí! ¡Es el vagón correcto!',
    'train.levelDone': '¡Bravo! ¡Todos los trenes han salido!',
    'train.continue': 'Continuar',
    'train.hintSing': 'Escucha el tren: {list}… ¿y después?',
    'train.hintPeriod': '¡Mira los vagones marcados: eso es lo que se repite!',
    'train.hintToken': '¡Prueba el vagón que baila!',
    'train.token.red': 'rojo', 'train.token.blue': 'azul', 'train.token.yellow': 'amarillo',
    'train.token.green': 'verde', 'train.token.purple': 'morado',
    'train.token.apple': 'manzana', 'train.token.banana': 'plátano', 'train.token.grapes': 'uvas',
    'train.token.pear': 'pera', 'train.token.watermelon': 'sandía',
    'train.intro.fruits': '¡Ahora el tren lleva frutas!',
    'train.intro.double': 'Mira bien: ¡a veces el mismo vagón viene dos veces seguidas!',
    'train.intro.middle': 'Atención: ¡esta vez el hueco puede estar en medio del tren!',
    'train.intro.period': 'Puedes llenarlos en el orden que quieras.',
    'train.intro.grow': 'Mira bien los puntos en los vagones: ¿cuántos hay?',
    'train.hintGrow': 'Mira el punto naranja: ¡en cada vagón hay un punto más!',
    'train.hintShrink': 'Mira el círculo naranja: ¡en cada vagón hay un punto menos!',
    'train.token.dots1': 'uno', 'train.token.dots2': 'dos', 'train.token.dots3': 'tres',
    'train.token.dots4': 'cuatro', 'train.token.dots5': 'cinco',
  },
  en: {
    'train.chooseLevel': 'Choose a level!',
    'train.level': 'Level {n}',
    'train.howTo': 'Look at the train: the wagons always follow the same way. Drag the right wagon into the gap!',
    'train.ask': 'A wagon is missing! Which one goes in the gap?',
    'train.askMany': 'Some wagons are missing! Fill all the gaps.',
    'train.free.intro': 'Invent the start of your train! Put two, three or four wagons, then press the green button.',
    'train.free.go': 'Make the train go',
    'train.free.full': 'Your start is full! Touch a wagon to take it out, or press the green button.',
    'train.free.needMore': 'Put at least two wagons!',
    'train.free.again': 'Again! To change a wagon, touch it to take it out.',
    'train.tray': 'Wagons to place',
    'train.empty': 'Empty wagon',
    'train.wrong.1': 'Hmm, not that one! Look at the train.',
    'train.wrong.2': 'Oops! The train doesn’t want it. Try another one!',
    'train.wrong.3': 'Almost! Look at the wagons and try again.',
    'train.right.1': 'Well done! Choo choo!',
    'train.right.2': 'Great! The train can leave!',
    'train.right.3': 'Yes! That’s the right wagon!',
    'train.levelDone': 'Well done! All the trains have left!',
    'train.continue': 'Continue',
    'train.hintSing': 'Listen to the train: {list}… and then?',
    'train.hintPeriod': 'Look at the circled wagons: that’s what repeats!',
    'train.hintToken': 'Try the wagon that’s dancing!',
    'train.token.red': 'red', 'train.token.blue': 'blue', 'train.token.yellow': 'yellow',
    'train.token.green': 'green', 'train.token.purple': 'purple',
    'train.token.apple': 'apple', 'train.token.banana': 'banana', 'train.token.grapes': 'grapes',
    'train.token.pear': 'pear', 'train.token.watermelon': 'watermelon',
    'train.intro.fruits': 'Now the train is carrying fruit!',
    'train.intro.double': 'Look closely: sometimes the same wagon comes twice in a row!',
    'train.intro.middle': 'Careful: this time the gap can be in the middle of the train!',
    'train.intro.period': 'You can fill them in any order you like.',
    'train.intro.grow': 'Look closely at the dots in the wagons: how many are there?',
    'train.hintGrow': 'Look at the orange dot: each wagon has one more dot!',
    'train.hintShrink': 'Look at the orange circle: each wagon has one dot less!',
    'train.token.dots1': 'one', 'train.token.dots2': 'two', 'train.token.dots3': 'three',
    'train.token.dots4': 'four', 'train.token.dots5': 'five',
  },
};
