// Duo Mémoire — the game's strings (fr / es / en). The title lives in meta.js.
export default {
  fr: {
    'memory.path': 'Retourne deux cartes. Trouve les cartes jumelles !',
    'memory.chooseLevel': 'Choisis un niveau.',
    'memory.level': 'Niveau {n}',
    'memory.card': 'Carte',
    'memory.continue': 'Continuer',
    'memory.levelDone': 'Bravo ! Tu as trouvé toutes les paires !',
    'memory.right.1': 'Une paire !',
    'memory.right.2': 'Bien joué !',
    'memory.right.3': 'Les jumelles !',
    'memory.clue': 'Regarde la carte qui bouge !',
    'memory.glow': 'Sa jumelle brille !',
    'memory.board': 'Bravo ! Toutes les paires !',
  },
  es: {
    'memory.path': 'Da la vuelta a dos cartas. ¡Encuentra las cartas gemelas!',
    'memory.chooseLevel': 'Elige un nivel.',
    'memory.level': 'Nivel {n}',
    'memory.card': 'Carta',
    'memory.continue': 'Continuar',
    'memory.levelDone': '¡Bravo! ¡Encontraste todas las parejas!',
    'memory.right.1': '¡Una pareja!',
    'memory.right.2': '¡Muy bien!',
    'memory.right.3': '¡Las gemelas!',
    'memory.clue': '¡Mira la carta que se mueve!',
    'memory.glow': '¡Su gemela brilla!',
    'memory.board': '¡Bravo! ¡Todas las parejas!',
  },
  en: {
    'memory.path': 'Turn over two cards. Find the twin cards!',
    'memory.chooseLevel': 'Choose a level.',
    'memory.level': 'Level {n}',
    'memory.card': 'Card',
    'memory.continue': 'Continue',
    'memory.levelDone': 'Well done! You found all the pairs!',
    'memory.right.1': 'A pair!',
    'memory.right.2': 'Well done!',
    'memory.right.3': 'The twins!',
    'memory.clue': 'Look at the card that moves!',
    'memory.glow': 'Its twin is shining!',
    'memory.board': 'Well done! All the pairs!',
  },
};
