// Everything "Formes & Silhouettes" says, in fr / es / en.
// (The title is in meta.js: the hub needs it before the game loads.)
// shapes.shape.<id>  = every shape in levels.js SHAPES (with its article, said aloud)
// shapes.object.<id> = every object in levels.js OBJECTS
// The round lines (questions, hints) come with each kind of round (steps (c)–(e)).
export default {
  fr: {
    'shapes.chooseLevel': 'Choisis un niveau !',
    'shapes.level': 'Niveau {n}',
    'shapes.levelDone': 'Bravo ! Tu connais bien les formes !',
    'shapes.continue': 'Continuer',
    'shapes.soon': 'Bientôt !',
    'shapes.intro.missing': 'Attention, regarde bien : il manque parfois un morceau !',
    'shapes.intro.turn': 'Touche une pièce pour la tourner !',
    'shapes.intro.lookalike': 'Attention, certaines pièces se ressemblent !',
    'shapes.intro.mirror': 'Fais pareil de l’autre côté, comme dans un miroir !',
    'shapes.intro.colors': 'Maintenant avec deux couleurs !',
    'shapes.shape.circle': 'le cercle', 'shapes.shape.square': 'le carré',
    'shapes.shape.rectangle': 'le rectangle', 'shapes.shape.bar': 'la barre',
    'shapes.shape.diamond': 'le losange', 'shapes.shape.triangle': 'le triangle',
    'shapes.shape.halfSquare': 'le demi-carré', 'shapes.shape.halfCircle': 'le demi-cercle',
    'shapes.shape.star': 'l’étoile', 'shapes.shape.heart': 'le cœur',
    'shapes.object.house': 'la maison', 'shapes.object.rabbit': 'le lapin',
    'shapes.object.car': 'la voiture', 'shapes.object.teapot': 'la théière',
    'shapes.object.rocket': 'la fusée', 'shapes.object.plane': 'l’avion',
    'shapes.object.fish': 'le poisson', 'shapes.object.boat': 'le bateau',
  },
  es: {
    'shapes.chooseLevel': '¡Elige un nivel!',
    'shapes.level': 'Nivel {n}',
    'shapes.levelDone': '¡Bravo! ¡Conoces muy bien las formas!',
    'shapes.continue': 'Continuar',
    'shapes.soon': '¡Pronto!',
    'shapes.intro.missing': '¡Atención, mira bien: a veces falta un trozo!',
    'shapes.intro.turn': '¡Toca una pieza para girarla!',
    'shapes.intro.lookalike': '¡Atención, algunas piezas se parecen!',
    'shapes.intro.mirror': '¡Haz lo mismo del otro lado, como en un espejo!',
    'shapes.intro.colors': '¡Ahora con dos colores!',
    'shapes.shape.circle': 'el círculo', 'shapes.shape.square': 'el cuadrado',
    'shapes.shape.rectangle': 'el rectángulo', 'shapes.shape.bar': 'la barra',
    'shapes.shape.diamond': 'el rombo', 'shapes.shape.triangle': 'el triángulo',
    'shapes.shape.halfSquare': 'el medio cuadrado', 'shapes.shape.halfCircle': 'el medio círculo',
    'shapes.shape.star': 'la estrella', 'shapes.shape.heart': 'el corazón',
    'shapes.object.house': 'la casa', 'shapes.object.rabbit': 'el conejo',
    'shapes.object.car': 'el coche', 'shapes.object.teapot': 'la tetera',
    'shapes.object.rocket': 'el cohete', 'shapes.object.plane': 'el avión',
    'shapes.object.fish': 'el pez', 'shapes.object.boat': 'el barco',
  },
  en: {
    'shapes.chooseLevel': 'Choose a level!',
    'shapes.level': 'Level {n}',
    'shapes.levelDone': 'Well done! You know your shapes!',
    'shapes.continue': 'Continue',
    'shapes.soon': 'Coming soon!',
    'shapes.intro.missing': 'Look carefully: sometimes a piece is missing!',
    'shapes.intro.turn': 'Tap a piece to turn it!',
    'shapes.intro.lookalike': 'Careful, some pieces look alike!',
    'shapes.intro.mirror': 'Do the same on the other side, like in a mirror!',
    'shapes.intro.colors': 'Now with two colours!',
    'shapes.shape.circle': 'the circle', 'shapes.shape.square': 'the square',
    'shapes.shape.rectangle': 'the rectangle', 'shapes.shape.bar': 'the bar',
    'shapes.shape.diamond': 'the diamond', 'shapes.shape.triangle': 'the triangle',
    'shapes.shape.halfSquare': 'the half square', 'shapes.shape.halfCircle': 'the half circle',
    'shapes.shape.star': 'the star', 'shapes.shape.heart': 'the heart',
    'shapes.object.house': 'the house', 'shapes.object.rabbit': 'the rabbit',
    'shapes.object.car': 'the car', 'shapes.object.teapot': 'the teapot',
    'shapes.object.rocket': 'the rocket', 'shapes.object.plane': 'the plane',
    'shapes.object.fish': 'the fish', 'shapes.object.boat': 'the boat',
  },
};
