// Everything "Formes & Silhouettes" says, in fr / es / en.
// (The title is in meta.js: the hub needs it before the game loads.)
// shapes.shape.<id>  = every shape in levels.js SHAPES (with its article, said aloud)
// shapes.object.<id> = every object in levels.js OBJECTS
// shapes.clue.<id>  = a spoken clue for every shape (first hint)
export default {
  fr: {
    'shapes.chooseLevel': 'Choisis un niveau !',
    'shapes.level': 'Niveau {n}',
    'shapes.levelDone': 'Bravo ! Tu connais bien les formes !',
    'shapes.continue': 'Continuer',
    'shapes.soon': 'Bientôt !',
    'shapes.intro.missing': 'Attention, regarde bien : il manque parfois un morceau !',
    'shapes.intro.turn': 'Touche une pièce pour la tourner !',
    'shapes.intro.lookalike': 'Attention, certaines pièces se ressemblent !',
    'shapes.intro.mirror': 'Fais pareil de l’autre côté, comme dans un miroir !',
    'shapes.intro.colors': 'Maintenant avec deux couleurs !',
    'shapes.pieces': 'Les pièces',
    'shapes.wrong.1': 'Oups, pas là !', 'shapes.wrong.2': 'Hmm, pas ici !', 'shapes.wrong.3': 'Oh non, pas là !',
    'shapes.again.1': 'Essaie encore !', 'shapes.again.2': 'Presque ! Encore une fois !', 'shapes.again.3': 'Tu vas trouver !',
    'shapes.ask.sort': 'Range chaque forme dans son trou !',
    'shapes.sort.placed': 'Oui ! {A} !',
    'shapes.sort.find': 'Cherche le trou de la même forme !',
    'shapes.sort.glow': 'Mets {a} dans le trou qui brille !',
    'shapes.sort.done': 'Bravo ! Toutes les formes sont rangées !',
    'shapes.clue.circle': 'Le cercle est tout rond, sans coin.',
    'shapes.clue.square': 'Le carré a 4 côtés tous pareils.',
    'shapes.clue.rectangle': 'Le rectangle a 4 coins, et il est plus long que large.',
    'shapes.clue.bar': 'La barre est longue et toute fine.',
    'shapes.clue.diamond': 'Le losange a 4 pointes, comme un cerf-volant.',
    'shapes.clue.triangle': 'Le triangle a 3 coins.',
    'shapes.clue.halfSquare': 'Le demi-carré a 3 coins, dont un coin bien carré.',
    'shapes.clue.halfCircle': 'Le demi-cercle est rond d’un côté et plat de l’autre.',
    'shapes.clue.star': 'L’étoile a 5 pointes.',
    'shapes.clue.heart': 'Le cœur a 2 bosses en haut et une pointe en bas.',
    'shapes.intro.shadow': 'Glisse le dessin sur son ombre !',
    'shapes.ask.shadow': 'Où est l’ombre de {a} ?',
    'shapes.shadow.right': 'Oui ! C’est l’ombre de {a} !',
    'shapes.clue.shadow': 'Regarde bien la forme de {a}.',
    'shapes.clue.missing': 'Regarde bien : il manque un morceau à deux ombres !',
    'shapes.shadow.glow': 'Regarde l’ombre qui brille !',
    'shapes.shadow.dance': 'Pose {a} sur l’ombre qui brille !',
    'shapes.shape.circle': 'le cercle', 'shapes.shape.square': 'le carré',
    'shapes.shape.rectangle': 'le rectangle', 'shapes.shape.bar': 'la barre',
    'shapes.shape.diamond': 'le losange', 'shapes.shape.triangle': 'le triangle',
    'shapes.shape.halfSquare': 'le demi-carré', 'shapes.shape.halfCircle': 'le demi-cercle',
    'shapes.shape.star': 'l’étoile', 'shapes.shape.heart': 'le cœur',
    'shapes.object.house': 'la maison', 'shapes.object.rabbit': 'le lapin',
    'shapes.object.car': 'la voiture', 'shapes.object.teapot': 'la théière',
    'shapes.object.rocket': 'la fusée', 'shapes.object.plane': 'l’avion',
    'shapes.object.fish': 'le poisson', 'shapes.object.boat': 'le bateau',
  },
  es: {
    'shapes.chooseLevel': '¡Elige un nivel!',
    'shapes.level': 'Nivel {n}',
    'shapes.levelDone': '¡Bravo! ¡Conoces muy bien las formas!',
    'shapes.continue': 'Continuar',
    'shapes.soon': '¡Pronto!',
    'shapes.intro.missing': '¡Atención, mira bien: a veces falta un trozo!',
    'shapes.intro.turn': '¡Toca una pieza para girarla!',
    'shapes.intro.lookalike': '¡Atención, algunas piezas se parecen!',
    'shapes.intro.mirror': '¡Haz lo mismo del otro lado, como en un espejo!',
    'shapes.intro.colors': '¡Ahora con dos colores!',
    'shapes.pieces': 'Las piezas',
    'shapes.wrong.1': '¡Uy, ahí no!', 'shapes.wrong.2': '¡Mmm, aquí no!', 'shapes.wrong.3': '¡Oh no, ahí no!',
    'shapes.again.1': '¡Inténtalo otra vez!', 'shapes.again.2': '¡Casi! ¡Otra vez!', 'shapes.again.3': '¡Lo vas a encontrar!',
    'shapes.ask.sort': '¡Pon cada forma en su agujero!',
    'shapes.sort.placed': '¡Sí! ¡{A}!',
    'shapes.sort.find': '¡Busca el agujero con la misma forma!',
    'shapes.sort.glow': '¡Pon {a} en el agujero que brilla!',
    'shapes.sort.done': '¡Bravo! ¡Todas las formas están en su sitio!',
    'shapes.clue.circle': 'El círculo es todo redondo, sin esquinas.',
    'shapes.clue.square': 'El cuadrado tiene 4 lados iguales.',
    'shapes.clue.rectangle': 'El rectángulo tiene 4 esquinas y es más largo que ancho.',
    'shapes.clue.bar': 'La barra es larga y muy fina.',
    'shapes.clue.diamond': 'El rombo tiene 4 puntas, como una cometa.',
    'shapes.clue.triangle': 'El triángulo tiene 3 esquinas.',
    'shapes.clue.halfSquare': 'El medio cuadrado tiene 3 esquinas, y una es bien cuadrada.',
    'shapes.clue.halfCircle': 'El medio círculo es redondo de un lado y plano del otro.',
    'shapes.clue.star': 'La estrella tiene 5 puntas.',
    'shapes.clue.heart': 'El corazón tiene 2 bultos arriba y una punta abajo.',
    'shapes.intro.shadow': '¡Arrastra el dibujo sobre su sombra!',
    'shapes.ask.shadow': '¿Dónde está la sombra de {a}?',
    'shapes.shadow.right': '¡Sí! ¡Es la sombra de {a}!',
    'shapes.clue.shadow': 'Mira bien la forma de {a}.',
    'shapes.clue.missing': '¡Mira bien: a dos sombras les falta un trozo!',
    'shapes.shadow.glow': '¡Mira la sombra que brilla!',
    'shapes.shadow.dance': '¡Pon {a} sobre la sombra que brilla!',
    'shapes.shape.circle': 'el círculo', 'shapes.shape.square': 'el cuadrado',
    'shapes.shape.rectangle': 'el rectángulo', 'shapes.shape.bar': 'la barra',
    'shapes.shape.diamond': 'el rombo', 'shapes.shape.triangle': 'el triángulo',
    'shapes.shape.halfSquare': 'el medio cuadrado', 'shapes.shape.halfCircle': 'el medio círculo',
    'shapes.shape.star': 'la estrella', 'shapes.shape.heart': 'el corazón',
    'shapes.object.house': 'la casa', 'shapes.object.rabbit': 'el conejo',
    'shapes.object.car': 'el coche', 'shapes.object.teapot': 'la tetera',
    'shapes.object.rocket': 'el cohete', 'shapes.object.plane': 'el avión',
    'shapes.object.fish': 'el pez', 'shapes.object.boat': 'el barco',
  },
  en: {
    'shapes.chooseLevel': 'Choose a level!',
    'shapes.level': 'Level {n}',
    'shapes.levelDone': 'Well done! You know your shapes!',
    'shapes.continue': 'Continue',
    'shapes.soon': 'Coming soon!',
    'shapes.intro.missing': 'Look carefully: sometimes a piece is missing!',
    'shapes.intro.turn': 'Tap a piece to turn it!',
    'shapes.intro.lookalike': 'Careful, some pieces look alike!',
    'shapes.intro.mirror': 'Do the same on the other side, like in a mirror!',
    'shapes.intro.colors': 'Now with two colours!',
    'shapes.pieces': 'The pieces',
    'shapes.wrong.1': 'Oops, not there!', 'shapes.wrong.2': 'Hmm, not here!', 'shapes.wrong.3': 'Oh no, not there!',
    'shapes.again.1': 'Try again!', 'shapes.again.2': 'Almost! One more time!', 'shapes.again.3': 'You’ll find it!',
    'shapes.ask.sort': 'Put each shape in its hole!',
    'shapes.sort.placed': 'Yes! {A}!',
    'shapes.sort.find': 'Look for the hole with the same shape!',
    'shapes.sort.glow': 'Put {a} in the shining hole!',
    'shapes.sort.done': 'Well done! Every shape is in its place!',
    'shapes.clue.circle': 'The circle is all round, with no corners.',
    'shapes.clue.square': 'The square has 4 sides, all the same.',
    'shapes.clue.rectangle': 'The rectangle has 4 corners, and it is longer than it is wide.',
    'shapes.clue.bar': 'The bar is long and very thin.',
    'shapes.clue.diamond': 'The diamond has 4 points, like a kite.',
    'shapes.clue.triangle': 'The triangle has 3 corners.',
    'shapes.clue.halfSquare': 'The half square has 3 corners, and one is a square corner.',
    'shapes.clue.halfCircle': 'The half circle is round on one side and flat on the other.',
    'shapes.clue.star': 'The star has 5 points.',
    'shapes.clue.heart': 'The heart has 2 bumps on top and a point at the bottom.',
    'shapes.intro.shadow': 'Drag the picture onto its shadow!',
    'shapes.ask.shadow': 'Where is the shadow of {a}?',
    'shapes.shadow.right': 'Yes! It’s the shadow of {a}!',
    'shapes.clue.shadow': 'Look carefully at the shape of {a}.',
    'shapes.clue.missing': 'Look carefully: two shadows are missing a piece!',
    'shapes.shadow.glow': 'Look at the shining shadow!',
    'shapes.shadow.dance': 'Put {a} on the shining shadow!',
    'shapes.shape.circle': 'the circle', 'shapes.shape.square': 'the square',
    'shapes.shape.rectangle': 'the rectangle', 'shapes.shape.bar': 'the bar',
    'shapes.shape.diamond': 'the diamond', 'shapes.shape.triangle': 'the triangle',
    'shapes.shape.halfSquare': 'the half square', 'shapes.shape.halfCircle': 'the half circle',
    'shapes.shape.star': 'the star', 'shapes.shape.heart': 'the heart',
    'shapes.object.house': 'the house', 'shapes.object.rabbit': 'the rabbit',
    'shapes.object.car': 'the car', 'shapes.object.teapot': 'the teapot',
    'shapes.object.rocket': 'the rocket', 'shapes.object.plane': 'the plane',
    'shapes.object.fish': 'the fish', 'shapes.object.boat': 'the boat',
  },
};
