// Everything "Formes & Silhouettes" says, in fr / es / en.
// (The title is in meta.js: the hub needs it before the game loads.)
// shapes.shape.<id>   = every shape in levels.js SHAPES (with its article, said aloud)
// shapes.clue.<id>    = a spoken clue for every shape (first hint)
// shapes.picture.<id> = every puzzle picture in levels.js PICTURES
export default {
  fr: {
    'shapes.chooseLevel': 'Choisis un niveau !',
    'shapes.level': 'Niveau {n}',
    'shapes.levelDone': 'Bravo ! Tu connais bien les formes !',
    'shapes.continue': 'Continuer',
    'shapes.soon': 'Bientôt !',
    'shapes.intro.turn': 'Touche une pièce pour la tourner !',
    'shapes.intro.lookalike': 'Attention, certaines pièces se ressemblent !',
    'shapes.pieces': 'Les pièces',
    'shapes.wrong.1': 'Oups, pas là !',
    'shapes.wrong.2': 'Hmm, pas ici !',
    'shapes.wrong.3': 'Oh non, pas là !',
    'shapes.again.1': 'Essaie encore !',
    'shapes.again.2': 'Presque ! Encore une fois !',
    'shapes.again.3': 'Tu vas trouver !',
    'shapes.clue.circle': 'Le cercle est tout rond, sans coin.',
    'shapes.clue.square': 'Le carré a 4 côtés tous pareils.',
    'shapes.clue.rectangle': 'Le rectangle a 4 coins, et il est plus long que large.',
    'shapes.clue.bar': 'La barre est longue et toute fine.',
    'shapes.clue.diamond': 'Le losange a 4 pointes, comme un cerf-volant.',
    'shapes.clue.triangle': 'Le triangle a 3 coins.',
    'shapes.clue.halfSquare': 'Le demi-carré a 3 coins, dont un coin bien carré.',
    'shapes.clue.halfCircle': 'Le demi-cercle est rond d’un côté et plat de l’autre.',
    'shapes.clue.star': 'L’étoile a 5 pointes.',
    'shapes.clue.heart': 'Le cœur a 2 bosses en haut et une pointe en bas.',
    'shapes.ask.puzzle': 'Remplis le dessin avec les pièces !',
    'shapes.puzzle.turn': 'Bonne forme ! Touche-la pour la tourner.',
    'shapes.puzzle.glow': 'Pose {a} sur la forme qui brille !',
    'shapes.puzzle.danceTurn': 'Touche la pièce pour la tourner, puis pose-la sur la forme qui brille !',
    'shapes.puzzle.done': 'Bravo ! C’est {a} !',
    'shapes.picture.house': 'la maison',
    'shapes.picture.tree': 'l’arbre',
    'shapes.picture.iceCream': 'la glace',
    'shapes.picture.flower': 'la fleur',
    'shapes.picture.fish': 'le poisson',
    'shapes.picture.rocket': 'la fusée',
    'shapes.picture.car': 'la voiture',
    'shapes.picture.sailboat': 'le voilier',
    'shapes.picture.tower': 'la tour',
    'shapes.picture.cottage': 'la petite maison',
    'shapes.picture.pot': 'le pot de fleur',
    'shapes.picture.mushroom': 'le champignon',
    'shapes.picture.train': 'le train',
    'shapes.picture.cat': 'le chat',
    'shapes.picture.bird': 'l’oiseau',
    'shapes.picture.crown': 'la couronne',
    'shapes.picture.robot': 'le robot',
    'shapes.picture.snail': 'l’escargot',
    'shapes.picture.turtle': 'la tortue',
    'shapes.picture.chalet': 'le chalet',
    'shapes.picture.butterfly': 'le papillon',
    'shapes.picture.cup': 'la tasse',
    'shapes.picture.plane': 'l’avion',
    'shapes.picture.lighthouse': 'le phare',
    'shapes.shape.circle': 'le cercle',
    'shapes.shape.square': 'le carré',
    'shapes.shape.rectangle': 'le rectangle',
    'shapes.shape.bar': 'la barre',
    'shapes.shape.diamond': 'le losange',
    'shapes.shape.triangle': 'le triangle',
    'shapes.shape.halfSquare': 'le demi-carré',
    'shapes.shape.halfCircle': 'le demi-cercle',
    'shapes.shape.star': 'l’étoile',
    'shapes.shape.heart': 'le cœur',
    'shapes.placed': 'Oui ! {A} !',
    'shapes.shape.parallelogram': 'le parallélogramme',
    'shapes.shape.hexagon': 'l’hexagone',
    'shapes.shape.longTriangle': 'le grand triangle',
    'shapes.shape.quarterCircle': 'le quart de cercle',
    'shapes.shape.trapezoid': 'le trapèze',
    'shapes.shape.pentagon': 'le pentagone',
    'shapes.clue.parallelogram': 'Le parallélogramme est un rectangle penché.',
    'shapes.clue.hexagon': 'L’hexagone a 6 côtés, comme une case de ruche.',
    'shapes.clue.longTriangle': 'Le grand triangle est long et fin, avec un coin carré.',
    'shapes.clue.quarterCircle': 'Le quart de cercle est comme une part de pizza : un coin carré et un bord rond.',
    'shapes.clue.trapezoid': 'Le trapèze ressemble à un toit coupé en haut.',
    'shapes.clue.pentagon': 'Le pentagone a 5 côtés, comme une maison.',
  },
  es: {
    'shapes.chooseLevel': '¡Elige un nivel!',
    'shapes.level': 'Nivel {n}',
    'shapes.levelDone': '¡Bravo! ¡Conoces muy bien las formas!',
    'shapes.continue': 'Continuar',
    'shapes.soon': '¡Pronto!',
    'shapes.intro.turn': '¡Toca una pieza para girarla!',
    'shapes.intro.lookalike': '¡Atención, algunas piezas se parecen!',
    'shapes.pieces': 'Las piezas',
    'shapes.wrong.1': '¡Uy, ahí no!',
    'shapes.wrong.2': '¡Mmm, aquí no!',
    'shapes.wrong.3': '¡Oh no, ahí no!',
    'shapes.again.1': '¡Inténtalo otra vez!',
    'shapes.again.2': '¡Casi! ¡Otra vez!',
    'shapes.again.3': '¡Lo vas a encontrar!',
    'shapes.clue.circle': 'El círculo es todo redondo, sin esquinas.',
    'shapes.clue.square': 'El cuadrado tiene 4 lados iguales.',
    'shapes.clue.rectangle': 'El rectángulo tiene 4 esquinas y es más largo que ancho.',
    'shapes.clue.bar': 'La barra es larga y muy fina.',
    'shapes.clue.diamond': 'El rombo tiene 4 puntas, como una cometa.',
    'shapes.clue.triangle': 'El triángulo tiene 3 esquinas.',
    'shapes.clue.halfSquare': 'El medio cuadrado tiene 3 esquinas, y una es bien cuadrada.',
    'shapes.clue.halfCircle': 'El medio círculo es redondo de un lado y plano del otro.',
    'shapes.clue.star': 'La estrella tiene 5 puntas.',
    'shapes.clue.heart': 'El corazón tiene 2 bultos arriba y una punta abajo.',
    'shapes.ask.puzzle': '¡Completa el dibujo con las piezas!',
    'shapes.puzzle.turn': '¡Buena forma! Tócala para girarla.',
    'shapes.puzzle.glow': '¡Pon {a} sobre la forma que brilla!',
    'shapes.puzzle.danceTurn': '¡Toca la pieza para girarla, y luego ponla sobre la forma que brilla!',
    'shapes.puzzle.done': '¡Bravo! ¡Es {a}!',
    'shapes.picture.house': 'la casa',
    'shapes.picture.tree': 'el árbol',
    'shapes.picture.iceCream': 'el helado',
    'shapes.picture.flower': 'la flor',
    'shapes.picture.fish': 'el pez',
    'shapes.picture.rocket': 'el cohete',
    'shapes.picture.car': 'el coche',
    'shapes.picture.sailboat': 'el velero',
    'shapes.picture.tower': 'la torre',
    'shapes.picture.cottage': 'la casita',
    'shapes.picture.pot': 'la maceta',
    'shapes.picture.mushroom': 'la seta',
    'shapes.picture.train': 'el tren',
    'shapes.picture.cat': 'el gato',
    'shapes.picture.bird': 'el pájaro',
    'shapes.picture.crown': 'la corona',
    'shapes.picture.robot': 'el robot',
    'shapes.picture.snail': 'el caracol',
    'shapes.picture.turtle': 'la tortuga',
    'shapes.picture.chalet': 'la cabaña',
    'shapes.picture.butterfly': 'la mariposa',
    'shapes.picture.cup': 'la taza',
    'shapes.picture.plane': 'el avión',
    'shapes.picture.lighthouse': 'el faro',
    'shapes.shape.circle': 'el círculo',
    'shapes.shape.square': 'el cuadrado',
    'shapes.shape.rectangle': 'el rectángulo',
    'shapes.shape.bar': 'la barra',
    'shapes.shape.diamond': 'el rombo',
    'shapes.shape.triangle': 'el triángulo',
    'shapes.shape.halfSquare': 'el medio cuadrado',
    'shapes.shape.halfCircle': 'el medio círculo',
    'shapes.shape.star': 'la estrella',
    'shapes.shape.heart': 'el corazón',
    'shapes.placed': '¡Sí! ¡{A}!',
    'shapes.shape.parallelogram': 'el paralelogramo',
    'shapes.shape.hexagon': 'el hexágono',
    'shapes.shape.longTriangle': 'el triángulo largo',
    'shapes.shape.quarterCircle': 'el cuarto de círculo',
    'shapes.shape.trapezoid': 'el trapecio',
    'shapes.shape.pentagon': 'el pentágono',
    'shapes.clue.parallelogram': 'El paralelogramo es un rectángulo inclinado.',
    'shapes.clue.hexagon': 'El hexágono tiene 6 lados, como una celda de colmena.',
    'shapes.clue.longTriangle': 'El triángulo largo es largo y fino, con una esquina cuadrada.',
    'shapes.clue.quarterCircle': 'El cuarto de círculo es como un trozo de pizza: una esquina cuadrada y un borde redondo.',
    'shapes.clue.trapezoid': 'El trapecio parece un tejado cortado arriba.',
    'shapes.clue.pentagon': 'El pentágono tiene 5 lados, como una casa.',
  },
  en: {
    'shapes.chooseLevel': 'Choose a level!',
    'shapes.level': 'Level {n}',
    'shapes.levelDone': 'Well done! You know your shapes!',
    'shapes.continue': 'Continue',
    'shapes.soon': 'Coming soon!',
    'shapes.intro.turn': 'Tap a piece to turn it!',
    'shapes.intro.lookalike': 'Careful, some pieces look alike!',
    'shapes.pieces': 'The pieces',
    'shapes.wrong.1': 'Oops, not there!',
    'shapes.wrong.2': 'Hmm, not here!',
    'shapes.wrong.3': 'Oh no, not there!',
    'shapes.again.1': 'Try again!',
    'shapes.again.2': 'Almost! One more time!',
    'shapes.again.3': 'You’ll find it!',
    'shapes.clue.circle': 'The circle is all round, with no corners.',
    'shapes.clue.square': 'The square has 4 sides, all the same.',
    'shapes.clue.rectangle': 'The rectangle has 4 corners, and it is longer than it is wide.',
    'shapes.clue.bar': 'The bar is long and very thin.',
    'shapes.clue.diamond': 'The diamond has 4 points, like a kite.',
    'shapes.clue.triangle': 'The triangle has 3 corners.',
    'shapes.clue.halfSquare': 'The half square has 3 corners, and one is a square corner.',
    'shapes.clue.halfCircle': 'The half circle is round on one side and flat on the other.',
    'shapes.clue.star': 'The star has 5 points.',
    'shapes.clue.heart': 'The heart has 2 bumps on top and a point at the bottom.',
    'shapes.ask.puzzle': 'Fill the picture with the pieces!',
    'shapes.puzzle.turn': 'Right shape! Tap it to turn it.',
    'shapes.puzzle.glow': 'Put {a} on the shining shape!',
    'shapes.puzzle.danceTurn': 'Tap the piece to turn it, then put it on the shining shape!',
    'shapes.puzzle.done': 'Well done! It’s {a}!',
    'shapes.picture.house': 'the house',
    'shapes.picture.tree': 'the tree',
    'shapes.picture.iceCream': 'the ice cream',
    'shapes.picture.flower': 'the flower',
    'shapes.picture.fish': 'the fish',
    'shapes.picture.rocket': 'the rocket',
    'shapes.picture.car': 'the car',
    'shapes.picture.sailboat': 'the sailboat',
    'shapes.picture.tower': 'the tower',
    'shapes.picture.cottage': 'the cottage',
    'shapes.picture.pot': 'the flower pot',
    'shapes.picture.mushroom': 'the mushroom',
    'shapes.picture.train': 'the train',
    'shapes.picture.cat': 'the cat',
    'shapes.picture.bird': 'the bird',
    'shapes.picture.crown': 'the crown',
    'shapes.picture.robot': 'the robot',
    'shapes.picture.snail': 'the snail',
    'shapes.picture.turtle': 'the turtle',
    'shapes.picture.chalet': 'the chalet',
    'shapes.picture.butterfly': 'the butterfly',
    'shapes.picture.cup': 'the cup',
    'shapes.picture.plane': 'the plane',
    'shapes.picture.lighthouse': 'the lighthouse',
    'shapes.shape.circle': 'the circle',
    'shapes.shape.square': 'the square',
    'shapes.shape.rectangle': 'the rectangle',
    'shapes.shape.bar': 'the bar',
    'shapes.shape.diamond': 'the diamond',
    'shapes.shape.triangle': 'the triangle',
    'shapes.shape.halfSquare': 'the half square',
    'shapes.shape.halfCircle': 'the half circle',
    'shapes.shape.star': 'the star',
    'shapes.shape.heart': 'the heart',
    'shapes.placed': 'Yes! {A}!',
    'shapes.shape.parallelogram': 'the parallelogram',
    'shapes.shape.hexagon': 'the hexagon',
    'shapes.shape.longTriangle': 'the long triangle',
    'shapes.shape.quarterCircle': 'the quarter circle',
    'shapes.shape.trapezoid': 'the trapezoid',
    'shapes.shape.pentagon': 'the pentagon',
    'shapes.clue.parallelogram': 'The parallelogram is a leaning rectangle.',
    'shapes.clue.hexagon': 'The hexagon has 6 sides, like a beehive cell.',
    'shapes.clue.longTriangle': 'The long triangle is long and thin, with a square corner.',
    'shapes.clue.quarterCircle': 'The quarter circle is like a slice of pizza: a square corner and a round edge.',
    'shapes.clue.trapezoid': 'The trapezoid looks like a roof cut flat at the top.',
    'shapes.clue.pentagon': 'The pentagon has 5 sides, like a house.',
  },
};
